# fmt: off
# Code for generating Sm90_tma.py

import os

f = open(os.path.join(os.path.split(__file__)[0], "Sm90_tma.py"), "w")


def forbid_trailing_spaces(line):
    assert not line.endswith(" "), line
    return line


def write_chunk(chunk):
    f.write("\n")
    f.write("#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####\n")

    lines = [forbid_trailing_spaces(line) for line in chunk.split("\n")]
    for line in lines:
        f.write(line)
        f.write("\n")


f.write("# fmt: off\n")


write_chunk('''
from __future__ import annotations

from .Sm90_fwd import *
from .Sm90_smem import *
from .Sm90_tensorMap import *
from .Sm90_tma_impl import make_basic_tma

from exo.API import *
from exo.platforms.cuda import *

from .Sm90_internal_util import *
''')



_all = ["Sm90_tensorMap"]
_instr_defs = []


def append_instr(n_dims: int, to_gmem: bool, is_multicast: bool, is_reduce: bool):
    if to_gmem:
        if is_reduce:
            instr_name = f"Sm90_tma_reduce_add_{n_dims}d"
            docstr = f"Atomically add a {n_dims}-D tile GMEM += SMEM"
        else:
            instr_name = f"Sm90_tma_store_{n_dims}d"
            docstr = f"Copy a {n_dims}-D tile in SMEM into GMEM"
    else:
        if is_multicast:
            instr_name = f"Sm90_tma_load_multicast_{n_dims}d"
            docstr = f"""Copy a {n_dims}-D tile in GMEM into SMEM, broadcast to ncta-many CTAs

    The participating CTAs have blockIdx values increasing by cta_stride
    in sequence, e.g. ncta=4, cta_stride=2 could mean
    CTAs 0, 2, 4, 6, or CTAs 1, 3, 5, 7.
"""
        else:
            instr_name = f"Sm90_tma_load_{n_dims}d"
            docstr = f"Copy a {n_dims}-D tile in GMEM into SMEM"

    lines = []
    lines.append("@instr")
    lines.append(f"class {instr_name}(make_basic_tma(n_dims={n_dims}, to_gmem={to_gmem}, is_multicast={is_multicast}, is_reduce={is_reduce})):")
    lines.append(f'    """{docstr}"""')
    lines.append("    def behavior(")

    indent = "        "
    sizes_csv = ", ".join(f"size{n}" for n in range(0, n_dims))
    sizes_ncta_csv = ", ".join(
        "size0 // ncta" if n == 0 else f"size{n}" for n in range(0, n_dims)
    )

    # Size parameters (template instance parameters)
    if is_multicast:
        lines.append(indent + "ncta: size,")
    for n in range(n_dims):
        lines.append(indent + f"size{n}: size,")

    # SMEM and GMEM data parameters.
    smem_comments = [indent + f"# @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0"]
    smem_comments.append(indent + "# Must be densely packed.")
    if is_multicast:
        smem_comments.append(indent + f"# Each [{sizes_csv}] shard is owned by 1 CTA.")
        gmem_comments = [indent + f"# @ Sm90_tensorMap(swizzle, {sizes_ncta_csv})"]
        gmem_comments.append(indent + "# (The tile is subdivided on dim 0; each sub-tile is copied by 1 CTA).")
    else:
        gmem_comments = [indent + f"# @ Sm90_tensorMap(swizzle, {sizes_csv})"]
    gmem_comments.append(indent + "# Additional 1's are allowed in the size list.")

    if to_gmem:
        lines.extend(gmem_comments)
        lines.append(indent + f"dst: [R][{sizes_csv}],")
        lines.extend(smem_comments)
        lines.append(indent + f"src: [R][{sizes_csv}],")
        smem_name = "src"
        gmem_name = "dst"
    else:
        lines.extend(smem_comments)
        if is_multicast:
            lines.append(indent + f"dst: [R][ncta, {sizes_csv}],")
        else:
            lines.append(indent + f"dst: [R][{sizes_csv}],")
        lines.extend(gmem_comments)
        lines.append(indent + f"src: [R][{sizes_csv}],")
        smem_name = "dst"
        gmem_name = "src"
    lines.append("    ):")
    # End behavior function signature.

    # Add stride assertions.
    lines.append(indent + "# Must be tightly-packed on inner-most dimension")
    lines.append(indent + f"assert stride(dst, {n_dims-1}) == 1")
    lines.append(indent + f"assert stride(src, {n_dims-1}) == 1")
    if n_dims > 1:
        lines.append(indent + "# SMEM must be tightly-packed on all dimensions")
        if n_dims > 2:
            lines.append(indent + "# XXX Exo cannot do this assert for > 2 dimensions")
        lines.append(indent + f"assert stride({smem_name}, {n_dims-2}) == size{n_dims-1}")

    # Define loop nest
    lines.append("")
    if is_multicast:
        lines.append(indent + "# seq vs cuda_threads has no effect here; just for clarity.")
        lines.append(indent + "for cta in cuda_threads(0, ncta, unit=cuda_cta_in_cluster):")
        indent += "    "
    for n in range(0, n_dims):
        lines.append(indent + f"for i{n} in seq(0, size{n}):")
        indent += "    "

    # Assign or Reduce stmt
    idxs_csv = ", ".join(f"i{n}" for n in range(0, n_dims))
    if is_multicast:
        lines.append(indent + f"dst[cta, {idxs_csv}] = src[{idxs_csv}]")
    elif is_reduce:
        lines.append(indent + f"dst[{idxs_csv}] += src[{idxs_csv}]")
    else:
        lines.append(indent + f"dst[{idxs_csv}] = src[{idxs_csv}]")

    # We also have to define the stub instance(...) function.
    if is_multicast:
        lines.append(f"""
    def instance(
        self,
        # Instance template parameters
        ncta, {sizes_csv}, *,
        # Extra template parameters; usually swizzle=128.
        cta_stride: int, smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, ({sizes_ncta_csv}, ))
        self.instance_impl(ncta, ({sizes_csv}, ), smem_box, cta_stride, swizzle)
""")
    else:
        lines.append(f"""
    def instance(
        self,
        # Instance template parameters
        {sizes_csv}, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, ({sizes_csv}, ))
        self.instance_impl(1, ({sizes_csv}, ), smem_box, 1, swizzle)
""")

    # Push definitions to lists, to be written out at the end of the script.
    _all.append(instr_name)
    _instr_defs.append("\n".join(lines))

for n_dims in range(1, 6):
    append_instr(n_dims, to_gmem=False, is_multicast=False, is_reduce=False)
    append_instr(n_dims, to_gmem=False, is_multicast=True, is_reduce=False)
    append_instr(n_dims, to_gmem=True, is_multicast=False, is_reduce=False)
    append_instr(n_dims, to_gmem=True, is_multicast=False, is_reduce=True)


write_chunk(
"__all__ = [\n    " + ",\n    ".join(repr(n) for n in _all) + "\n]\n"
)

for i, _def in enumerate(_instr_defs):
    variant_comment = f"# TMA instr variant {i+1}/{len(_instr_defs)}\n"
    write_chunk(variant_comment + _def)


f.write("# End of file. Prevent black newline reformatting.\n")
f.close()
