# fmt: off
# Code for generating Sm90_tk_mma.py

import os

f = open(os.path.join(os.path.split(__file__)[0], "Sm90_tk_mma.py"), "w")


def forbid_trailing_spaces(line):
    assert not line.endswith(" "), line
    return line


def write_chunk(chunk):
    f.write("\n")
    f.write("#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####\n")

    lines = [forbid_trailing_spaces(line) for line in chunk.split("\n")]
    for line in lines:
        f.write(line)
        f.write("\n")


f.write("# fmt: off\n")


_all = ["CudaTkWarpTile", "Sm90_TkRmemTileA", "Sm90_TkRmemTileD"]
_instr_defs = []


def append_instr(a_mode: str, b_mode: str):
    instr_name = f"Sm90_tk_mma_{a_mode}_{b_mode}"

    M = "64"
    if a_mode == "rmem":
        A_comment = "register tiles"
    elif a_mode == "row":
        A_comment = "row-major SMEM"
    else:
        A_comment = "column-major SMEM (trans-a)"
    if b_mode == "row":
        N = "64 * N64"
        B_comment = "row-major SMEM (trans-b)"
    else:
        N = "N"
        B_comment = "column-major SMEM"

    lines = []
    lines.append(f"# m({M}) x n({N}) x k(K) matrix multiply-accumulate")
    lines.append(f"# A in {A_comment}, B in {B_comment}")

    lines.append("@instr")
    lines.append(f"class {instr_name}(make_basic_mma({a_mode!r}, {b_mode!r})):")
    lines.append("    def behavior(")

    indent = "        "

    # N/K instance template parameters.
    if b_mode == "row":
        lines.append(indent + "N64: size,  # N / 64")
    else:
        lines.append(indent + "N: size,")
    lines.append(indent + "K: size,")

    # D parameter
    lines.append(indent + "# D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps")
    lines.append(indent + f"D: [R][4, 16, {N}],")

    # A parameter
    if a_mode == "row":
        lines.append(indent + "# A @ Sm90_SmemSwizzled(swizzle), indexed as [m, k]")
        lines.append(indent + f"A: [R][{M}, K],")
    elif a_mode == "col":
        lines.append(indent + "# A @ Sm90_SmemSwizzled(128), indexed as [k, m]")
        lines.append(indent + "A: [R][K, 64] @ Sm90_SmemSwizzled(128),")
    else:
        assert a_mode == "rmem"
        lines.append(indent + "# A @ Sm90_TkRmemTileA(K), split on M dim into 4 warps")
        lines.append(indent + "A: [R][4, 16, K],")

    # B parameter
    if b_mode == "row":
        lines.append(indent + "# B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]")
        lines.append(indent + "B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),")
    else:
        assert b_mode == "col"
        lines.append(indent + "# B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]")
        lines.append(indent + f"B: [R][{N}, K],")

    lines.append("    ):")

    # Add SMEM info.
    lines.append(indent + '# Note, SMEM stride requirements enforced in codegen.')
    lines.append(indent + '# Right-most ("leading") dimension must be densely packed.')
    lines.append(indent + '# The other ("strided") dimension must be strided by `swizzle` BYTES,')
    lines.append(indent + '# i.e. swizzle / sizeof(Element) elements.')

    # Define behavior loop nest.
    m = "m_warp * 16 + mi"
    lines.append(indent + "for m_warp in seq(0, 4):")
    indent += "    "
    lines.append(indent + "for mi in seq(0, 16):")
    indent += "    "
    if b_mode == "row":
        lines.append(indent + "for no in seq(0, N64):")
        indent += "    "
        lines.append(indent + "for ni in seq(0, 64):")
        indent += "    "
        n = "no * 64 + ni"
    else:
        lines.append(indent + "for n in seq(0, N):")
        indent += "    "
        n = "n"
    lines.append(indent + "for k in seq(0, K):")
    indent += "    "

    # Define behavior += stmt.
    lines.append(indent + f"D[m_warp, mi, {n}] += (")
    if a_mode == "row":
        lines.append(indent + f"    A[{m}, k]")
    elif a_mode == "col":
        lines.append(indent + f"    A[k, {m}]")
    else:
        assert a_mode == "rmem"
        lines.append(indent + f"    A[m_warp, mi, k]")
    if b_mode == "row":
        lines.append(indent + f"  * B[no, k, ni]")
    else:
        lines.append(indent + f"  * B[{n}, k]")
    lines.append(indent + ")")
    _all.append(instr_name)
    _instr_defs.append("\n".join(lines))


for b_mode in ("col", "row"):
    for a_mode in ("row", "rmem", "col"):
        append_instr(a_mode, b_mode)


write_chunk('''
from __future__ import annotations

from .Sm90_fwd import *
from .Sm90_smem import *

from exo.API import *
from exo.platforms.cuda import *
from exo.platforms.cuda_tk import CudaTkWarpTile

from .Sm90_tk_mma_impl import Sm90_TkRmemTileA, Sm90_TkRmemTileD, make_basic_mma

''')

write_chunk(
"__all__ = [\n    " + ",\n    ".join(repr(n) for n in _all) + "\n]\n"
)

for i, _def in enumerate(_instr_defs):
    variant_comment = f"# wgmma.mma_async instr variant {i+1}/{len(_instr_defs)}\n"
    write_chunk(variant_comment + _def)


f.write("# End of file. Prevent black newline reformatting.\n")
f.close()
