# fmt: off

#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####

from __future__ import annotations

from .Sm90_fwd import *
from .Sm90_smem import *
from .Sm90_tensorMap import *
from .Sm90_tma_impl import make_basic_tma

from exo.API import *
from exo.platforms.cuda import *

from .Sm90_internal_util import *


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
__all__ = [
    'Sm90_tensorMap',
    'Sm90_tma_load_1d',
    'Sm90_tma_load_multicast_1d',
    'Sm90_tma_store_1d',
    'Sm90_tma_reduce_add_1d',
    'Sm90_tma_load_2d',
    'Sm90_tma_load_multicast_2d',
    'Sm90_tma_store_2d',
    'Sm90_tma_reduce_add_2d',
    'Sm90_tma_load_3d',
    'Sm90_tma_load_multicast_3d',
    'Sm90_tma_store_3d',
    'Sm90_tma_reduce_add_3d',
    'Sm90_tma_load_4d',
    'Sm90_tma_load_multicast_4d',
    'Sm90_tma_store_4d',
    'Sm90_tma_reduce_add_4d',
    'Sm90_tma_load_5d',
    'Sm90_tma_load_multicast_5d',
    'Sm90_tma_store_5d',
    'Sm90_tma_reduce_add_5d'
]


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 1/20
@instr
class Sm90_tma_load_1d(make_basic_tma(n_dims=1, to_gmem=False, is_multicast=False, is_reduce=False)):
    """Copy a 1-D tile in GMEM into SMEM"""
    def behavior(
        size0: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        dst: [R][size0],
        # @ Sm90_tensorMap(swizzle, size0)
        # Additional 1's are allowed in the size list.
        src: [R][size0],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(dst, 0) == 1
        assert stride(src, 0) == 1

        for i0 in seq(0, size0):
            dst[i0] = src[i0]

    def instance(
        self,
        # Control value template parameters
        size0, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, ))
        self.instance_impl(1, (size0, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 2/20
@instr
class Sm90_tma_load_multicast_1d(make_basic_tma(n_dims=1, to_gmem=False, is_multicast=True, is_reduce=False)):
    """Copy a 1-D tile in GMEM into SMEM, broadcast to ncta-many CTAs

    The participating CTAs have blockIdx values increasing by cta_stride
    in sequence, e.g. ncta=4, cta_stride=2 could mean
    CTAs 0, 2, 4, 6, or CTAs 1, 3, 5, 7.
"""
    def behavior(
        ncta: size,
        size0: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        # Each [size0] shard is owned by 1 CTA.
        dst: [R][ncta, size0],
        # @ Sm90_tensorMap(swizzle, size0 // ncta)
        # (The tile is subdivided on dim 0; each sub-tile is copied by 1 CTA).
        # Additional 1's are allowed in the size list.
        src: [R][size0],
    ):
        # Must be tightly-packed on inner-most dimension
        # NB multicast asserts skip left-most dim of SMEM (the CTA dimension)
        assert stride(dst, 1) == 1
        assert stride(src, 0) == 1

        # seq vs cuda_threads has no effect here; just for clarity.
        for cta in cuda_threads(0, ncta, unit=cuda_cta_in_cluster):
            for i0 in seq(0, size0):
                dst[cta, i0] = src[i0]

    def instance(
        self,
        # Control value template parameters
        ncta, size0, *,
        # Extra template parameters; usually swizzle=128.
        cta_stride: int, smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0 // ncta, ))
        self.instance_impl(ncta, (size0, ), smem_box, cta_stride, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 3/20
@instr
class Sm90_tma_store_1d(make_basic_tma(n_dims=1, to_gmem=True, is_multicast=False, is_reduce=False)):
    """Copy a 1-D tile in SMEM into GMEM"""
    def behavior(
        size0: size,
        # @ Sm90_tensorMap(swizzle, size0)
        # Additional 1's are allowed in the size list.
        dst: [R][size0],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 0) == 1
        assert stride(dst, 0) == 1

        for i0 in seq(0, size0):
            dst[i0] = src[i0]

    def instance(
        self,
        # Control value template parameters
        size0, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, ))
        self.instance_impl(1, (size0, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 4/20
@instr
class Sm90_tma_reduce_add_1d(make_basic_tma(n_dims=1, to_gmem=True, is_multicast=False, is_reduce=True)):
    """Atomically add a 1-D tile GMEM += SMEM"""
    def behavior(
        size0: size,
        # @ Sm90_tensorMap(swizzle, size0)
        # Additional 1's are allowed in the size list.
        dst: [R][size0],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 0) == 1
        assert stride(dst, 0) == 1

        for i0 in seq(0, size0):
            dst[i0] += src[i0]

    def instance(
        self,
        # Control value template parameters
        size0, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, ))
        self.instance_impl(1, (size0, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 5/20
@instr
class Sm90_tma_load_2d(make_basic_tma(n_dims=2, to_gmem=False, is_multicast=False, is_reduce=False)):
    """Copy a 2-D tile in GMEM into SMEM"""
    def behavior(
        size0: size,
        size1: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        dst: [R][size0, size1],
        # @ Sm90_tensorMap(swizzle, size0, size1)
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(dst, 1) == 1
        assert stride(src, 1) == 1
        # SMEM must be tightly-packed on all dimensions
        assert stride(dst, 0) == size1

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                dst[i0, i1] = src[i0, i1]

    def instance(
        self,
        # Control value template parameters
        size0, size1, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, ))
        self.instance_impl(1, (size0, size1, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 6/20
@instr
class Sm90_tma_load_multicast_2d(make_basic_tma(n_dims=2, to_gmem=False, is_multicast=True, is_reduce=False)):
    """Copy a 2-D tile in GMEM into SMEM, broadcast to ncta-many CTAs

    The participating CTAs have blockIdx values increasing by cta_stride
    in sequence, e.g. ncta=4, cta_stride=2 could mean
    CTAs 0, 2, 4, 6, or CTAs 1, 3, 5, 7.
"""
    def behavior(
        ncta: size,
        size0: size,
        size1: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        # Each [size0, size1] shard is owned by 1 CTA.
        dst: [R][ncta, size0, size1],
        # @ Sm90_tensorMap(swizzle, size0 // ncta, size1)
        # (The tile is subdivided on dim 0; each sub-tile is copied by 1 CTA).
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1],
    ):
        # Must be tightly-packed on inner-most dimension
        # NB multicast asserts skip left-most dim of SMEM (the CTA dimension)
        assert stride(dst, 2) == 1
        assert stride(src, 1) == 1
        # SMEM must be tightly-packed on all dimensions
        assert stride(dst, 1) == size1

        # seq vs cuda_threads has no effect here; just for clarity.
        for cta in cuda_threads(0, ncta, unit=cuda_cta_in_cluster):
            for i0 in seq(0, size0):
                for i1 in seq(0, size1):
                    dst[cta, i0, i1] = src[i0, i1]

    def instance(
        self,
        # Control value template parameters
        ncta, size0, size1, *,
        # Extra template parameters; usually swizzle=128.
        cta_stride: int, smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0 // ncta, size1, ))
        self.instance_impl(ncta, (size0, size1, ), smem_box, cta_stride, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 7/20
@instr
class Sm90_tma_store_2d(make_basic_tma(n_dims=2, to_gmem=True, is_multicast=False, is_reduce=False)):
    """Copy a 2-D tile in SMEM into GMEM"""
    def behavior(
        size0: size,
        size1: size,
        # @ Sm90_tensorMap(swizzle, size0, size1)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 1) == 1
        assert stride(dst, 1) == 1
        # SMEM must be tightly-packed on all dimensions
        assert stride(src, 0) == size1

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                dst[i0, i1] = src[i0, i1]

    def instance(
        self,
        # Control value template parameters
        size0, size1, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, ))
        self.instance_impl(1, (size0, size1, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 8/20
@instr
class Sm90_tma_reduce_add_2d(make_basic_tma(n_dims=2, to_gmem=True, is_multicast=False, is_reduce=True)):
    """Atomically add a 2-D tile GMEM += SMEM"""
    def behavior(
        size0: size,
        size1: size,
        # @ Sm90_tensorMap(swizzle, size0, size1)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 1) == 1
        assert stride(dst, 1) == 1
        # SMEM must be tightly-packed on all dimensions
        assert stride(src, 0) == size1

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                dst[i0, i1] += src[i0, i1]

    def instance(
        self,
        # Control value template parameters
        size0, size1, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, ))
        self.instance_impl(1, (size0, size1, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 9/20
@instr
class Sm90_tma_load_3d(make_basic_tma(n_dims=3, to_gmem=False, is_multicast=False, is_reduce=False)):
    """Copy a 3-D tile in GMEM into SMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        dst: [R][size0, size1, size2],
        # @ Sm90_tensorMap(swizzle, size0, size1, size2)
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1, size2],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(dst, 2) == 1
        assert stride(src, 2) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(dst, 1) == size2

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    dst[i0, i1, i2] = src[i0, i1, i2]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, ))
        self.instance_impl(1, (size0, size1, size2, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 10/20
@instr
class Sm90_tma_load_multicast_3d(make_basic_tma(n_dims=3, to_gmem=False, is_multicast=True, is_reduce=False)):
    """Copy a 3-D tile in GMEM into SMEM, broadcast to ncta-many CTAs

    The participating CTAs have blockIdx values increasing by cta_stride
    in sequence, e.g. ncta=4, cta_stride=2 could mean
    CTAs 0, 2, 4, 6, or CTAs 1, 3, 5, 7.
"""
    def behavior(
        ncta: size,
        size0: size,
        size1: size,
        size2: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        # Each [size0, size1, size2] shard is owned by 1 CTA.
        dst: [R][ncta, size0, size1, size2],
        # @ Sm90_tensorMap(swizzle, size0 // ncta, size1, size2)
        # (The tile is subdivided on dim 0; each sub-tile is copied by 1 CTA).
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1, size2],
    ):
        # Must be tightly-packed on inner-most dimension
        # NB multicast asserts skip left-most dim of SMEM (the CTA dimension)
        assert stride(dst, 3) == 1
        assert stride(src, 2) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(dst, 2) == size2

        # seq vs cuda_threads has no effect here; just for clarity.
        for cta in cuda_threads(0, ncta, unit=cuda_cta_in_cluster):
            for i0 in seq(0, size0):
                for i1 in seq(0, size1):
                    for i2 in seq(0, size2):
                        dst[cta, i0, i1, i2] = src[i0, i1, i2]

    def instance(
        self,
        # Control value template parameters
        ncta, size0, size1, size2, *,
        # Extra template parameters; usually swizzle=128.
        cta_stride: int, smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0 // ncta, size1, size2, ))
        self.instance_impl(ncta, (size0, size1, size2, ), smem_box, cta_stride, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 11/20
@instr
class Sm90_tma_store_3d(make_basic_tma(n_dims=3, to_gmem=True, is_multicast=False, is_reduce=False)):
    """Copy a 3-D tile in SMEM into GMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        # @ Sm90_tensorMap(swizzle, size0, size1, size2)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1, size2],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1, size2],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 2) == 1
        assert stride(dst, 2) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(src, 1) == size2

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    dst[i0, i1, i2] = src[i0, i1, i2]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, ))
        self.instance_impl(1, (size0, size1, size2, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 12/20
@instr
class Sm90_tma_reduce_add_3d(make_basic_tma(n_dims=3, to_gmem=True, is_multicast=False, is_reduce=True)):
    """Atomically add a 3-D tile GMEM += SMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        # @ Sm90_tensorMap(swizzle, size0, size1, size2)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1, size2],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1, size2],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 2) == 1
        assert stride(dst, 2) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(src, 1) == size2

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    dst[i0, i1, i2] += src[i0, i1, i2]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, ))
        self.instance_impl(1, (size0, size1, size2, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 13/20
@instr
class Sm90_tma_load_4d(make_basic_tma(n_dims=4, to_gmem=False, is_multicast=False, is_reduce=False)):
    """Copy a 4-D tile in GMEM into SMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        dst: [R][size0, size1, size2, size3],
        # @ Sm90_tensorMap(swizzle, size0, size1, size2, size3)
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1, size2, size3],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(dst, 3) == 1
        assert stride(src, 3) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(dst, 2) == size3

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    for i3 in seq(0, size3):
                        dst[i0, i1, i2, i3] = src[i0, i1, i2, i3]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, size3, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, size3, ))
        self.instance_impl(1, (size0, size1, size2, size3, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 14/20
@instr
class Sm90_tma_load_multicast_4d(make_basic_tma(n_dims=4, to_gmem=False, is_multicast=True, is_reduce=False)):
    """Copy a 4-D tile in GMEM into SMEM, broadcast to ncta-many CTAs

    The participating CTAs have blockIdx values increasing by cta_stride
    in sequence, e.g. ncta=4, cta_stride=2 could mean
    CTAs 0, 2, 4, 6, or CTAs 1, 3, 5, 7.
"""
    def behavior(
        ncta: size,
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        # Each [size0, size1, size2, size3] shard is owned by 1 CTA.
        dst: [R][ncta, size0, size1, size2, size3],
        # @ Sm90_tensorMap(swizzle, size0 // ncta, size1, size2, size3)
        # (The tile is subdivided on dim 0; each sub-tile is copied by 1 CTA).
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1, size2, size3],
    ):
        # Must be tightly-packed on inner-most dimension
        # NB multicast asserts skip left-most dim of SMEM (the CTA dimension)
        assert stride(dst, 4) == 1
        assert stride(src, 3) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(dst, 3) == size3

        # seq vs cuda_threads has no effect here; just for clarity.
        for cta in cuda_threads(0, ncta, unit=cuda_cta_in_cluster):
            for i0 in seq(0, size0):
                for i1 in seq(0, size1):
                    for i2 in seq(0, size2):
                        for i3 in seq(0, size3):
                            dst[cta, i0, i1, i2, i3] = src[i0, i1, i2, i3]

    def instance(
        self,
        # Control value template parameters
        ncta, size0, size1, size2, size3, *,
        # Extra template parameters; usually swizzle=128.
        cta_stride: int, smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0 // ncta, size1, size2, size3, ))
        self.instance_impl(ncta, (size0, size1, size2, size3, ), smem_box, cta_stride, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 15/20
@instr
class Sm90_tma_store_4d(make_basic_tma(n_dims=4, to_gmem=True, is_multicast=False, is_reduce=False)):
    """Copy a 4-D tile in SMEM into GMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        # @ Sm90_tensorMap(swizzle, size0, size1, size2, size3)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1, size2, size3],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1, size2, size3],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 3) == 1
        assert stride(dst, 3) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(src, 2) == size3

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    for i3 in seq(0, size3):
                        dst[i0, i1, i2, i3] = src[i0, i1, i2, i3]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, size3, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, size3, ))
        self.instance_impl(1, (size0, size1, size2, size3, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 16/20
@instr
class Sm90_tma_reduce_add_4d(make_basic_tma(n_dims=4, to_gmem=True, is_multicast=False, is_reduce=True)):
    """Atomically add a 4-D tile GMEM += SMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        # @ Sm90_tensorMap(swizzle, size0, size1, size2, size3)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1, size2, size3],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1, size2, size3],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 3) == 1
        assert stride(dst, 3) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(src, 2) == size3

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    for i3 in seq(0, size3):
                        dst[i0, i1, i2, i3] += src[i0, i1, i2, i3]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, size3, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, size3, ))
        self.instance_impl(1, (size0, size1, size2, size3, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 17/20
@instr
class Sm90_tma_load_5d(make_basic_tma(n_dims=5, to_gmem=False, is_multicast=False, is_reduce=False)):
    """Copy a 5-D tile in GMEM into SMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        size4: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        dst: [R][size0, size1, size2, size3, size4],
        # @ Sm90_tensorMap(swizzle, size0, size1, size2, size3, size4)
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1, size2, size3, size4],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(dst, 4) == 1
        assert stride(src, 4) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(dst, 3) == size4

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    for i3 in seq(0, size3):
                        for i4 in seq(0, size4):
                            dst[i0, i1, i2, i3, i4] = src[i0, i1, i2, i3, i4]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, size3, size4, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, size3, size4, ))
        self.instance_impl(1, (size0, size1, size2, size3, size4, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 18/20
@instr
class Sm90_tma_load_multicast_5d(make_basic_tma(n_dims=5, to_gmem=False, is_multicast=True, is_reduce=False)):
    """Copy a 5-D tile in GMEM into SMEM, broadcast to ncta-many CTAs

    The participating CTAs have blockIdx values increasing by cta_stride
    in sequence, e.g. ncta=4, cta_stride=2 could mean
    CTAs 0, 2, 4, 6, or CTAs 1, 3, 5, 7.
"""
    def behavior(
        ncta: size,
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        size4: size,
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        # Each [size0, size1, size2, size3, size4] shard is owned by 1 CTA.
        dst: [R][ncta, size0, size1, size2, size3, size4],
        # @ Sm90_tensorMap(swizzle, size0 // ncta, size1, size2, size3, size4)
        # (The tile is subdivided on dim 0; each sub-tile is copied by 1 CTA).
        # Additional 1's are allowed in the size list.
        src: [R][size0, size1, size2, size3, size4],
    ):
        # Must be tightly-packed on inner-most dimension
        # NB multicast asserts skip left-most dim of SMEM (the CTA dimension)
        assert stride(dst, 5) == 1
        assert stride(src, 4) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(dst, 4) == size4

        # seq vs cuda_threads has no effect here; just for clarity.
        for cta in cuda_threads(0, ncta, unit=cuda_cta_in_cluster):
            for i0 in seq(0, size0):
                for i1 in seq(0, size1):
                    for i2 in seq(0, size2):
                        for i3 in seq(0, size3):
                            for i4 in seq(0, size4):
                                dst[cta, i0, i1, i2, i3, i4] = src[i0, i1, i2, i3, i4]

    def instance(
        self,
        # Control value template parameters
        ncta, size0, size1, size2, size3, size4, *,
        # Extra template parameters; usually swizzle=128.
        cta_stride: int, smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0 // ncta, size1, size2, size3, size4, ))
        self.instance_impl(ncta, (size0, size1, size2, size3, size4, ), smem_box, cta_stride, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 19/20
@instr
class Sm90_tma_store_5d(make_basic_tma(n_dims=5, to_gmem=True, is_multicast=False, is_reduce=False)):
    """Copy a 5-D tile in SMEM into GMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        size4: size,
        # @ Sm90_tensorMap(swizzle, size0, size1, size2, size3, size4)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1, size2, size3, size4],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1, size2, size3, size4],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 4) == 1
        assert stride(dst, 4) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(src, 3) == size4

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    for i3 in seq(0, size3):
                        for i4 in seq(0, size4):
                            dst[i0, i1, i2, i3, i4] = src[i0, i1, i2, i3, i4]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, size3, size4, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, size3, size4, ))
        self.instance_impl(1, (size0, size1, size2, size3, size4, ), smem_box, 1, swizzle)


#### Autogenerated by gen_Sm90_tma.py; do not hand-edit! ####
# TMA instr variant 20/20
@instr
class Sm90_tma_reduce_add_5d(make_basic_tma(n_dims=5, to_gmem=True, is_multicast=False, is_reduce=True)):
    """Atomically add a 5-D tile GMEM += SMEM"""
    def behavior(
        size0: size,
        size1: size,
        size2: size,
        size3: size,
        size4: size,
        # @ Sm90_tensorMap(swizzle, size0, size1, size2, size3, size4)
        # Additional 1's are allowed in the size list.
        dst: [R][size0, size1, size2, size3, size4],
        # @ Sm90_SmemSwizzled(swizzle), or CudaSmemLinear if swizzle == 0
        # Must be densely packed.
        src: [R][size0, size1, size2, size3, size4],
    ):
        # Must be tightly-packed on inner-most dimension
        assert stride(src, 4) == 1
        assert stride(dst, 4) == 1
        # SMEM must be tightly-packed on all dimensions
        # XXX Exo cannot do this assert for > 2 dimensions
        assert stride(src, 3) == size4

        for i0 in seq(0, size0):
            for i1 in seq(0, size1):
                for i2 in seq(0, size2):
                    for i3 in seq(0, size3):
                        for i4 in seq(0, size4):
                            dst[i0, i1, i2, i3, i4] += src[i0, i1, i2, i3, i4]

    def instance(
        self,
        # Control value template parameters
        size0, size1, size2, size3, size4, *,
        # Extra template parameters; usually swizzle=128.
        smem_box: Optional[Tuple[int]] = None, swizzle: int = 128,
    ):
        smem_box = self._validate_smem_box(smem_box, (size0, size1, size2, size3, size4, ))
        self.instance_impl(1, (size0, size1, size2, size3, size4, ), smem_box, 1, swizzle)

# End of file. Prevent black newline reformatting.
