# fmt: off

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####

from __future__ import annotations

from .Sm90_fwd import *
from .Sm90_smem import *

from exo.API import *
from exo.platforms.cuda import *
from exo.platforms.cuda_tk import CudaTkWarpTile
from exo.scalars import f16, f32

from .Sm90_tk_mma_impl import Sm90_TkRmemTileA, Sm90_TkRmemTileD, make_basic_mma



#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####

@instr
class Sm90_tk_zero_scale_d(InstrInfo):
    """Triggers the tile to be zeroed in the next mma instruction.

    """
    valid_num_types = {(f16, ), (f32, )}

    def behavior(N: size, D: [R][4, 16, N]):
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for n in seq(0, N):
                    D[m_warp, mi, n] = 0

    def instance(self, N):
        self.instr_tl = wgmma_zero_instr
        self.coll_unit = cuda_warpgroup
        self.access_info["D"].mem = Sm90_TkRmemTileD(N)
        self.access_info["D"].out_of_order = False
        self.access_info["D"].distributed_coll_units = (cuda_warp, )

    def codegen(self, args):
        return [f"{args.D.index(get_scale_d=True)} = 0;"]


#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
__all__ = [
    'CudaTkWarpTile',
    'Sm90_TkRmemTileA',
    'Sm90_TkRmemTileD',
    'Sm90_tk_zero_scale_d',
    'Sm90_tk_mma_row_col',
    'Sm90_tk_mma_rmem_col',
    'Sm90_tk_mma_col_col',
    'Sm90_tk_mma_row_row',
    'Sm90_tk_mma_rmem_row',
    'Sm90_tk_mma_col_row'
]


#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 1/6
@instr
class Sm90_tk_mma_row_col(make_basic_mma('row', 'col')):
    """"m(64) x n(N) x k(K) matrix multiply-accumulate

    A in row-major SMEM, B in column-major SMEM"""
    def behavior(
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, N],
        # A @ Sm90_SmemSwizzled(swizzle), indexed as [m, k]
        A: [R][64, K],
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for n in seq(0, N):
                    for k in seq(0, K):
                        D[m_warp, mi, n] += (
                            A[m_warp * 16 + mi, k]
                          * B[n, k]
                        )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 2/6
@instr
class Sm90_tk_mma_rmem_col(make_basic_mma('rmem', 'col')):
    """"m(64) x n(N) x k(K) matrix multiply-accumulate

    A in register tiles, B in column-major SMEM"""
    def behavior(
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, N],
        # A @ Sm90_TkRmemTileA(K), split on M dim into 4 warps
        A: [R][4, 16, K],
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for n in seq(0, N):
                    for k in seq(0, K):
                        D[m_warp, mi, n] += (
                            A[m_warp, mi, k]
                          * B[n, k]
                        )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 3/6
@instr
class Sm90_tk_mma_col_col(make_basic_mma('col', 'col')):
    """"m(64) x n(N) x k(K) matrix multiply-accumulate

    A in column-major SMEM (trans-a), B in column-major SMEM"""
    def behavior(
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, N],
        # A @ Sm90_SmemSwizzled(128), indexed as [k, m]
        A: [R][K, 64] @ Sm90_SmemSwizzled(128),
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for n in seq(0, N):
                    for k in seq(0, K):
                        D[m_warp, mi, n] += (
                            A[k, m_warp * 16 + mi]
                          * B[n, k]
                        )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 4/6
@instr
class Sm90_tk_mma_row_row(make_basic_mma('row', 'row')):
    """"m(64) x n(64 * N64) x k(K) matrix multiply-accumulate

    A in row-major SMEM, B in row-major SMEM (trans-b)"""
    def behavior(
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, 64 * N64],
        # A @ Sm90_SmemSwizzled(swizzle), indexed as [m, k]
        A: [R][64, K],
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for no in seq(0, N64):
                    for ni in seq(0, 64):
                        for k in seq(0, K):
                            D[m_warp, mi, no * 64 + ni] += (
                                A[m_warp * 16 + mi, k]
                              * B[no, k, ni]
                            )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 5/6
@instr
class Sm90_tk_mma_rmem_row(make_basic_mma('rmem', 'row')):
    """"m(64) x n(64 * N64) x k(K) matrix multiply-accumulate

    A in register tiles, B in row-major SMEM (trans-b)"""
    def behavior(
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, 64 * N64],
        # A @ Sm90_TkRmemTileA(K), split on M dim into 4 warps
        A: [R][4, 16, K],
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for no in seq(0, N64):
                    for ni in seq(0, 64):
                        for k in seq(0, K):
                            D[m_warp, mi, no * 64 + ni] += (
                                A[m_warp, mi, k]
                              * B[no, k, ni]
                            )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 6/6
@instr
class Sm90_tk_mma_col_row(make_basic_mma('col', 'row')):
    """"m(64) x n(64 * N64) x k(K) matrix multiply-accumulate

    A in column-major SMEM (trans-a), B in row-major SMEM (trans-b)"""
    def behavior(
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, 64 * N64],
        # A @ Sm90_SmemSwizzled(128), indexed as [k, m]
        A: [R][K, 64] @ Sm90_SmemSwizzled(128),
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for no in seq(0, N64):
                    for ni in seq(0, 64):
                        for k in seq(0, K):
                            D[m_warp, mi, no * 64 + ni] += (
                                A[k, m_warp * 16 + mi]
                              * B[no, k, ni]
                            )
# End of file. Prevent black newline reformatting.
