# fmt: off

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####

from __future__ import annotations

from .Sm90_fwd import *
from .Sm90_smem import *

from exo.API import *
from exo.platforms.cuda import *
from exo.platforms.cuda_tk import CudaTkWarpTile

from .Sm90_tk_mma_impl import Sm90_TkRmemTileA, Sm90_TkRmemTileD, make_basic_mma



#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
__all__ = [
    'CudaTkWarpTile',
    'Sm90_TkRmemTileA',
    'Sm90_TkRmemTileD',
    'Sm90_tk_mma_row_col_m64',
    'Sm90_tk_mma_row_col',
    'Sm90_tk_mma_rmem_col_m64',
    'Sm90_tk_mma_rmem_col',
    'Sm90_tk_mma_col_col_m64',
    'Sm90_tk_mma_row_row_m64',
    'Sm90_tk_mma_row_row',
    'Sm90_tk_mma_rmem_row_m64',
    'Sm90_tk_mma_rmem_row',
    'Sm90_tk_mma_col_row_m64'
]


#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 1/10
# m(64) x n(N) x k(K) matrix multiply-accumulate
# A in row-major SMEM, B in column-major SMEM
@instr
class Sm90_tk_mma_row_col_m64(make_basic_mma('row', 'col', True)):
    def behavior(
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, N],
        # A @ Sm90_SmemSwizzled(swizzle), indexed as [m, k]
        A: [R][64, K],
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for n in seq(0, N):
                    for k in seq(0, K):
                        D[m_warp, mi, n] += (
                            A[m_warp * 16 + mi, k]
                          * B[n, k]
                        )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 2/10
# m(64 * M64) x n(N) x k(K) matrix multiply-accumulate
# A in row-major SMEM, B in column-major SMEM
@instr
class Sm90_tk_mma_row_col(make_basic_mma('row', 'col', False)):
    def behavior(
        M64: size,  # M / 64
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), indexed as [w, m // 64, m % 16, n]
        # where `w` is the index of the warp in the warpgroup,
        # which owns rows with 16 * w <= (m % 64) <= 16 * w + 15
        D: [R][4, M64, 16, N],
        # A @ Sm90_SmemSwizzled(swizzle), indexed as [m, k]
        A: [R][64 * M64, K],
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for mo in seq(0, M64):
            for m_warp in seq(0, 4):
                for mi in seq(0, 16):
                    for n in seq(0, N):
                        for k in seq(0, K):
                            D[m_warp, mo, mi, n] += (
                                A[mo * 64 + m_warp * 16 + mi, k]
                              * B[n, k]
                            )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 3/10
# m(64) x n(N) x k(K) matrix multiply-accumulate
# A in register tiles, B in column-major SMEM
@instr
class Sm90_tk_mma_rmem_col_m64(make_basic_mma('rmem', 'col', True)):
    def behavior(
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, N],
        # A @ Sm90_TkRmemTileA(K), split on M dim into 4 warps
        A: [R][4, 16, K],
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for n in seq(0, N):
                    for k in seq(0, K):
                        D[m_warp, mi, n] += (
                            A[m_warp, mi, k]
                          * B[n, k]
                        )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 4/10
# m(64 * M64) x n(N) x k(K) matrix multiply-accumulate
# A in register tiles, B in column-major SMEM
@instr
class Sm90_tk_mma_rmem_col(make_basic_mma('rmem', 'col', False)):
    def behavior(
        M64: size,  # M / 64
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), indexed as [w, m // 64, m % 16, n]
        # where `w` is the index of the warp in the warpgroup,
        # which owns rows with 16 * w <= (m % 64) <= 16 * w + 15
        D: [R][4, M64, 16, N],
        # A @ Sm90_TkRmemTileA(K), indexed as [w, m // 64, m % 16, k]
        # where `w` is the index of the warp in the warpgroup,
        # which owns rows with 16 * w <= (m % 64) <= 16 * w + 15
        A: [R][4, M64, 16, K],
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for mo in seq(0, M64):
            for m_warp in seq(0, 4):
                for mi in seq(0, 16):
                    for n in seq(0, N):
                        for k in seq(0, K):
                            D[m_warp, mo, mi, n] += (
                                A[m_warp, mo, mi, k]
                              * B[n, k]
                            )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 5/10
# m(64) x n(N) x k(K) matrix multiply-accumulate
# A in column-major SMEM (trans-a), B in column-major SMEM
@instr
class Sm90_tk_mma_col_col_m64(make_basic_mma('col', 'col', True)):
    def behavior(
        N: size,
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, N],
        # A @ Sm90_SmemSwizzled(128), indexed as [k, m]
        A: [R][K, 64] @ Sm90_SmemSwizzled(128),
        # B @ Sm90_SmemSwizzled(swizzle), indexed as [n, k]
        B: [R][N, K],
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for n in seq(0, N):
                    for k in seq(0, K):
                        D[m_warp, mi, n] += (
                            A[k, m_warp * 16 + mi]
                          * B[n, k]
                        )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 6/10
# m(64) x n(64 * N64) x k(K) matrix multiply-accumulate
# A in row-major SMEM, B in row-major SMEM (trans-b)
@instr
class Sm90_tk_mma_row_row_m64(make_basic_mma('row', 'row', True)):
    def behavior(
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, 64 * N64],
        # A @ Sm90_SmemSwizzled(swizzle), indexed as [m, k]
        A: [R][64, K],
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for no in seq(0, N64):
                    for ni in seq(0, 64):
                        for k in seq(0, K):
                            D[m_warp, mi, no * 64 + ni] += (
                                A[m_warp * 16 + mi, k]
                              * B[no, k, ni]
                            )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 7/10
# m(64 * M64) x n(64 * N64) x k(K) matrix multiply-accumulate
# A in row-major SMEM, B in row-major SMEM (trans-b)
@instr
class Sm90_tk_mma_row_row(make_basic_mma('row', 'row', False)):
    def behavior(
        M64: size,  # M / 64
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), indexed as [w, m // 64, m % 16, n]
        # where `w` is the index of the warp in the warpgroup,
        # which owns rows with 16 * w <= (m % 64) <= 16 * w + 15
        D: [R][4, M64, 16, 64 * N64],
        # A @ Sm90_SmemSwizzled(swizzle), indexed as [m, k]
        A: [R][64 * M64, K],
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for mo in seq(0, M64):
            for m_warp in seq(0, 4):
                for mi in seq(0, 16):
                    for no in seq(0, N64):
                        for ni in seq(0, 64):
                            for k in seq(0, K):
                                D[m_warp, mo, mi, no * 64 + ni] += (
                                    A[mo * 64 + m_warp * 16 + mi, k]
                                  * B[no, k, ni]
                                )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 8/10
# m(64) x n(64 * N64) x k(K) matrix multiply-accumulate
# A in register tiles, B in row-major SMEM (trans-b)
@instr
class Sm90_tk_mma_rmem_row_m64(make_basic_mma('rmem', 'row', True)):
    def behavior(
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, 64 * N64],
        # A @ Sm90_TkRmemTileA(K), split on M dim into 4 warps
        A: [R][4, 16, K],
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for no in seq(0, N64):
                    for ni in seq(0, 64):
                        for k in seq(0, K):
                            D[m_warp, mi, no * 64 + ni] += (
                                A[m_warp, mi, k]
                              * B[no, k, ni]
                            )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 9/10
# m(64 * M64) x n(64 * N64) x k(K) matrix multiply-accumulate
# A in register tiles, B in row-major SMEM (trans-b)
@instr
class Sm90_tk_mma_rmem_row(make_basic_mma('rmem', 'row', False)):
    def behavior(
        M64: size,  # M / 64
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), indexed as [w, m // 64, m % 16, n]
        # where `w` is the index of the warp in the warpgroup,
        # which owns rows with 16 * w <= (m % 64) <= 16 * w + 15
        D: [R][4, M64, 16, 64 * N64],
        # A @ Sm90_TkRmemTileA(K), indexed as [w, m // 64, m % 16, k]
        # where `w` is the index of the warp in the warpgroup,
        # which owns rows with 16 * w <= (m % 64) <= 16 * w + 15
        A: [R][4, M64, 16, K],
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for mo in seq(0, M64):
            for m_warp in seq(0, 4):
                for mi in seq(0, 16):
                    for no in seq(0, N64):
                        for ni in seq(0, 64):
                            for k in seq(0, K):
                                D[m_warp, mo, mi, no * 64 + ni] += (
                                    A[m_warp, mo, mi, k]
                                  * B[no, k, ni]
                                )

#### Autogenerated by gen_Sm90_tk_mma.py; do not hand-edit! ####
# wgmma.mma_async instr variant 10/10
# m(64) x n(64 * N64) x k(K) matrix multiply-accumulate
# A in column-major SMEM (trans-a), B in row-major SMEM (trans-b)
@instr
class Sm90_tk_mma_col_row_m64(make_basic_mma('col', 'row', True)):
    def behavior(
        N64: size,  # N / 64
        K: size,
        # D @ Sm90_TkRmemTileD(N), split on M dim into 4 warps
        D: [R][4, 16, 64 * N64],
        # A @ Sm90_SmemSwizzled(128), indexed as [k, m]
        A: [R][K, 64] @ Sm90_SmemSwizzled(128),
        # B @ Sm90_SmemSwizzled(128), indexed as [n // 64, k, n % 64]
        B: [R][N64, K, 64] @ Sm90_SmemSwizzled(128),
    ):
        # Note, SMEM stride requirements enforced in codegen.
        # Right-most ("leading") dimension must be densely packed.
        # The other ("strided") dimension must be strided by `swizzle` BYTES,
        # i.e. swizzle / sizeof(Element) elements.
        for m_warp in seq(0, 4):
            for mi in seq(0, 16):
                for no in seq(0, N64):
                    for ni in seq(0, 64):
                        for k in seq(0, K):
                            D[m_warp, mi, no * 64 + ni] += (
                                A[k, m_warp * 16 + mi]
                              * B[no, k, ni]
                            )
# End of file. Prevent black newline reformatting.
