#!/bin/bash

# Redirect output to stderr.
exec 1>&2

NB_FILES=$(git diff --cached --name-only --diff-filter=ACMR |
           grep ".*ipynb$")

while IFS= read -r line
do
  if [ -f "$line" ]
  then
    jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "$line"
    git add "$line"
  fi
done <<< "$NB_FILES"
