#! /usr/bin/env python3

"""
Camspork is written in C++ and is only needed for Exo sync_check functionality.
To avoid making Exo more difficult to build and install for users who don't
need this C++ functionality, camspork compiles itself just-in-time,
writing the C++ binaries into a temporary JIT directory, which should be

* The exocc output directory, set automatically be exocc if used
* pytest temporary directory, set automatically by Exo pytest compiler fixture
* Given on the command line, if this file is executed as the main module
* Given by the CAMSPORK_JIT_DIR environment variable (overrides all)

You may also compile libcamspork for standalone use by running this file.

This file quickly generates the temporary build.ninja file,
then invokes the ninja build tool to compile the binaries.

"""

import sys
import os
import shlex
import subprocess

_camspork_jit_directory_name = None
_env_var_name = "CAMSPORK_JIT_DIR"
_ninja_single_threaded = False
pytest_compiler_count = 1  # For Exo pytest use


def set_jit_dir(dirname):
    global _camspork_jit_directory_name
    assert dirname
    dirname = str(dirname)
    if _camspork_jit_directory_name is not None:
        assert (
            _camspork_jit_directory_name == dirname
        ), "Can only set camspork jit directory once"
    _camspork_jit_directory_name = dirname


def set_single_threaded(flag):
    global _ninja_single_threaded
    _ninja_single_threaded = bool(flag)


def get_jit_dir():
    name = os.environ.get(_env_var_name, _camspork_jit_directory_name)
    if name is None:
        raise ValueError(
            f"Export the {_env_var_name} environment variable to name "
            f"a directory for compiling temporary C++. "
            f"Concurrent processes should not share this directory."
        )
    return os.path.join(name, "camspork")


def get_src_path():
    thisdir = os.path.split(__file__)[0]
    return os.path.join(thisdir, "lib")


def get_libcamspork_path():
    return os.path.join(get_jit_dir(), "libcamspork.so")


def get_ninja_cmd_path():
    ninja = os.environ.get("EXO_NINJA") or "ninja"
    try:
        subprocess.check_call(["which", ninja], stdout=sys.stderr)
    except Exception as e:
        raise ValueError(
            f"\x1b[31m\x1b[1msync_check:\x1b[0m missing ninja-build {ninja!r}; "
            f"override with EXO_NINJA environment variable."
        ) from e
    return ninja


def get_ninja_build_path():
    return os.path.join(get_jit_dir(), "build.ninja")


def get_bin_path():
    return os.path.join(get_jit_dir(), "bin")


def get_cxx():
    cxx = os.environ.get("EXO_CXX") or os.environ.get("CXX") or "c++"
    try:
        subprocess.check_call(["which", cxx], stdout=sys.stderr)
    except Exception as e:
        raise ValueError(
            f"\x1b[31m\x1b[1msync_check:\x1b[0m missing C++ compiler {cxx!r}; "
            f"override with EXO_CXX or CXX environment variable."
        ) from e
    return cxx


# ninja has inconsistent quoting rules I don't fully understand.
# It seems we want to use Qarg whenever the value is parsed
# by a shell (e.g. specifying the nvcc bin) and we use
# Qpath when ninja itself needs to parse the file name,
# e.g. listing the depfile/input/output files for a build
# (i.e. what would become the $in/$out variable).
def Qarg(s):
    # Quote argument
    return shlex.quote(s).replace("$", "$$")


def Qpath(s):
    return s.replace("$ ", "$$ ").replace(" ", "$ ").replace(":", "$:")


def get_src_file_paths():
    src_root = get_src_path()
    src_paths = []
    for dname, _, fnames in os.walk(src_root):
        for fname in fnames:
            if fname.endswith(".cpp") or fname.endswith(".cu"):
                full_path = os.path.join(dname, fname)
                src_paths.append(full_path)

    assert src_paths, f"Exo packaging bug? No source files found in {src_root!r}"

    # NB sorting is really important for sanity in tricky C++ cases
    # involving ODR violations and weak symbols.
    src_paths.sort()
    return src_paths


def generate_ninja(src_file_paths, libcamspork_path):
    cxx = get_cxx()
    ninja_path = get_ninja_build_path()
    os.makedirs(os.path.split(ninja_path)[0], exist_ok=True)

    with open(ninja_path, "w") as build:
        build.write(
            f"""# Generated by {__file__!r}

rule cxx
  command = {Qarg(cxx)} -fdiagnostics-color=always -g -O2 -Wall -Wextra -Wconversion -Wno-sign-conversion -fPIC -g -std=c++17 $in -c -o $out -MD -MF $out.d
  depfile = $out.d

rule link_lib
  command = {Qarg(cxx)} $in -shared -o $out

"""
        )
        # Each C++ file found (in the Exo source tree) becomes an .o file
        # in the JIT's bin directory.
        bin_path = get_bin_path()
        obj_paths = []
        for i, src_path in enumerate(src_file_paths):
            src_dname, src_fname = os.path.split(src_path)
            obj_path = os.path.join(bin_path, f"{src_fname}.{len(obj_paths)}.o")
            obj_paths.append(obj_path)
            build.write(f"build {Qpath(obj_path)}: cxx {Qpath(src_path)}\n")

        # Link all the .o files together
        build.write(f"\n\nbuild {Qpath(libcamspork_path)}: link_lib")
        for obj_path in obj_paths:
            build.write(f" $\n    {Qpath(obj_path)}")
        build.write("\n")
    # build.ninja closed and flush upon with block exit.

    return ninja_path


def compile_libcamspork():
    libcamspork_path = get_libcamspork_path()
    src_file_paths = get_src_file_paths()
    ninja_path = generate_ninja(src_file_paths, libcamspork_path)
    ninja_cmds = [get_ninja_cmd_path(), "-f", ninja_path]
    if _ninja_single_threaded:
        ninja_cmds.append("-j1")
    subprocess.check_call(ninja_cmds)
    with open(os.path.join(get_jit_dir(), "compile_commands.json"), "w") as f:
        subprocess.check_call(ninja_cmds + ["-t", "compdb", "cxx"], stdout=f)
    return libcamspork_path


if __name__ == "__main__":
    if len(sys.argv) == 2:
        set_jit_dir(sys.argv[1])
    elif len(sys.argv) == 1 and _env_var_name in os.environ:
        pass
    else:
        sys.stderr.write("Wrapper for build, run with build directory name\n")
        exit(1)

    sys.stderr.write(f"Compiling {get_libcamspork_path()}\n")
    compile_libcamspork()
