# Code for generating tk_vec_ops.py

import os

from typing import List

f = open(os.path.join(os.path.split(__file__)[0], "tk_vec_ops.py"), "w")


def forbid_trailing_spaces(line):
    assert not line.endswith(" "), line
    return line


def write_chunk(chunk):
    f.write("\n")
    f.write("#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####\n")

    lines = [forbid_trailing_spaces(line) for line in chunk.split("\n")]
    for line in lines:
        f.write(line)
        f.write("\n")


_all = []
_all_comments = []
_instr_defs = []

f.write("# fmt: off\n")

write_chunk(
    """\
from __future__ import annotations
from exo.API import instr
from exo.scalars import ScalarInfo, inf

from exo.libs.externs import fabsf, fminf, fmaxf, relu, expf, exp2f, logf, log2f

from .tk_types import *

from .tk_vec_ops_impl import (
    basic_0ary_vec_op,
    basic_copy_layout_vec_op,
    basic_unary_vec_op,
    basic_binary_3op_vec_op,
    basic_binary_lhs_vec_op,
    basic_binary_rhs_vec_op,
    basic_binary_3op_vec_scalar_op,
    basic_binary_lhs_vec_scalar_op,
)

from ..cuda import CudaBasicDeviceVisible

"""
)


def gen_instr(
    name,
    base_name,
    kittens_op_name,
    body_stmt,
    arg_names: List[str],
    *,
    scalar_names: List[str] = (),
    valid_num_types="ScalarInfo.same()",
    kittens_constant_name: str = "",
    separate_layout: bool = False,
):
    args = []
    for nm in arg_names:
        if nm in scalar_names:
            comment = ""
            typ = "R @ CudaBasicDeviceVisible"
        else:
            layout_prefix = f"{nm}_" if separate_layout else ""
            comment = f"  # @ CudaTkWarpVec(length, {layout_prefix}layout)"
            typ = "[R][length]"
        args.append(f"\n        {nm}: {typ},{comment}")

    kittens_constant_name_line = ""
    if kittens_constant_name:
        kittens_constant_name_line = (
            f'\n    kittens_constant_name = "{kittens_constant_name}"'
        )

    _def = f"""@instr
class {name}({base_name}):{kittens_constant_name_line}
    kittens_op_name = \"{kittens_op_name}\"
    valid_num_types = {valid_num_types}

    def behavior(
        length: size,{''.join(args)}
    ):
        for i in seq(0, length):
            {body_stmt}
"""

    _all.append(name)
    _all_comments.append(str(body_stmt))
    _instr_defs.append(_def)


# Tile copy with optional type/precision conversion.
gen_instr(
    "cuda_tk_vec_copy",
    "basic_unary_vec_op",
    "copy",
    "dst[i] = src[i]",
    ("dst", "src"),
    valid_num_types="cuda_tk_valid_num_types_all_pairs",
)

# Tile copy with optional type/precision/layout conversion.
gen_instr(
    "cuda_tk_vec_copy_layout",
    "basic_copy_layout_vec_op",
    "copy",
    "dst[i] = src[i]",
    ("dst", "src"),
    valid_num_types="cuda_tk_valid_num_types_all_pairs",
    separate_layout=True,
)

# 0-ary ops (set to zero/one/neg_infty/pos_infty)
for name, value in (
    ("zero", "0"),
    ("one", "1"),
    ("pos_infty", "inf"),
    ("neg_infty", "-inf"),
):
    gen_instr(
        f"cuda_tk_vec_{name}",
        "basic_0ary_vec_op",
        name,
        f"dst[i] = {value}",
        ("dst",),
    )

for nm in ("pos_inf", "neg_inf"):
    _all.append(f"cuda_tk_vec_{nm}")
    _all_comments.append("For consistency with exo.inf")
    _instr_defs.append(f"cuda_tk_vec_{nm} = cuda_tk_vec_{nm}ty")


# Unary vec ops
unary_name_externs = [
    ("exp", "expf"),
    ("exp2", "exp2f"),
    ("log", "logf"),
    ("log2", "log2f"),
    ("abs", "fabsf"),
    ("relu", "relu"),
]
for name, extern in unary_name_externs:
    gen_instr(
        f"cuda_tk_vec_{name}",
        "basic_unary_vec_op",
        name,
        f"dst[i] = {extern}(src[i])",
        ("dst", "src"),
    )


# Binary vec ops, multiple forms
# dst = lhs op rhs [rhs could be a scalar]
# dst = dst op src [src could be a scalar]
# dst = src op dst
# dst += src [src could be a scalar]
binary_name_stmt = [
    ("max", "{dst}[i] = fmaxf({lhs}[i], {rhs}{rhs_idx})"),
    ("min", "{dst}[i] = fminf({lhs}[i], {rhs}{rhs_idx})"),
    ("add", "{dst}[i] = {lhs}[i] + {rhs}{rhs_idx}"),
    ("sub", "{dst}[i] = {lhs}[i] - {rhs}{rhs_idx}"),
    ("mul", "{dst}[i] = {lhs}[i] * {rhs}{rhs_idx}"),
    ("div", "{dst}[i] = {lhs}[i] / {rhs}{rhs_idx}"),
]

for name, stmt_fmt in binary_name_stmt:
    gen_instr(
        f"cuda_tk_vec_{name}_3op",
        "basic_binary_3op_vec_op",
        name,
        stmt_fmt.format(dst="dst", lhs="lhs", rhs="rhs", rhs_idx="[i]"),
        ("dst", "lhs", "rhs"),
    )
    gen_instr(
        f"cuda_tk_vec_{name}_3op_scalar",
        "basic_binary_3op_vec_scalar_op",
        name,
        stmt_fmt.format(dst="dst", lhs="lhs", rhs="rhs", rhs_idx=""),
        ("dst", "lhs", "rhs"),
        scalar_names=("rhs",),
    )
    if name == "add":
        gen_instr(
            f"cuda_tk_vec_{name}_reduce",
            "basic_binary_lhs_vec_op",
            name,
            "dst[i] += src[i]",
            ("dst", "src"),
        )
        gen_instr(
            f"cuda_tk_vec_{name}_reduce_scalar",
            "basic_binary_lhs_vec_scalar_op",
            name,
            "dst[i] += src",
            ("dst", "src"),
            scalar_names=("src",),
        )
    gen_instr(
        f"cuda_tk_vec_{name}_lhs",
        "basic_binary_lhs_vec_op",
        name,
        stmt_fmt.format(dst="dst", lhs="dst", rhs="src", rhs_idx="[i]"),
        ("dst", "src"),
    )
    gen_instr(
        f"cuda_tk_vec_{name}_lhs_scalar",
        "basic_binary_lhs_vec_scalar_op",
        name,
        stmt_fmt.format(dst="dst", lhs="dst", rhs="src", rhs_idx=""),
        ("dst", "src"),
        scalar_names=("src",),
    )
    gen_instr(
        f"cuda_tk_vec_{name}_rhs",
        "basic_binary_rhs_vec_op",
        name,
        stmt_fmt.format(dst="dst", lhs="src", rhs="dst", rhs_idx="[i]"),
        ("src", "dst"),
    )


#############################################################################
# Finalize file contents
#############################################################################

assert len(_all) == len(_all_comments)


all_lines = []
for nm, comment in zip(_all, _all_comments):
    comment = " ".join(comment.split())
    nm_repr = '"' + nm + '",'
    all_lines.append("    " + nm_repr + " " * (40 - len(nm_repr)) + "# " + comment)
all_lines_joined = "\n".join(all_lines)


write_chunk(
    f"""__all__ = [
{all_lines_joined}
]"""
)

for i, _def in enumerate(_instr_defs):
    variant_comment = f"# Vec op {i+1}/{len(_instr_defs)}\n"
    write_chunk(variant_comment + _def)


f.write("# End of file. Prevent black newline reformatting.\n")
f.close()
