# Code for generating tk_tile_ops.py

import os

from typing import List

f = open(os.path.join(os.path.split(__file__)[0], "tk_tile_ops.py"), "w")


def forbid_trailing_spaces(line):
    assert not line.endswith(" "), line
    return line


def write_chunk(chunk):
    f.write("\n")
    f.write("#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####\n")

    lines = [forbid_trailing_spaces(line) for line in chunk.split("\n")]
    for line in lines:
        f.write(line)
        f.write("\n")


_all = []
_all_comments = []
_instr_defs = []

f.write("# fmt: off\n")

write_chunk(
    """\
from __future__ import annotations
from exo.API import instr
from exo.scalars import ScalarInfo, inf

from exo.libs.externs import fabsf, fminf, fmaxf, relu, expf, exp2f, logf, log2f

from .tk_types import *

from .tk_tile_ops_impl import (
    basic_0ary_tile_op,
    basic_make_causal_op,
    basic_unary_tile_op,
    basic_binary_tile_op,
    basic_binary_lhs_tile_op,
    basic_binary_rhs_tile_op,
    basic_row_reduce_op,
    basic_col_reduce_op,
    basic_broadcast_row_op,
    basic_broadcast_col_op,
)

"""
)


def gen_instr(
    name,
    base_name,
    kittens_op_name,
    body_stmt,
    arg_names: List[str],
    *,
    row_vec_names: List[str] = (),
    col_vec_names: List[str] = (),
    valid_num_types="ScalarInfo.same()",
    prefix_lines: List[str] = (),
    kittens_constant_name: str = "",
):
    args = []
    for nm in arg_names:
        comment = '@ CudaTkWarpTile(rows, cols, layout="row")'
        typ = "[R][rows, cols]"
        if nm in row_vec_names:
            typ = "[R][cols]"
            comment += ".row_vec"
        if nm in col_vec_names:
            assert not nm in row_vec_names
            typ = "[R][rows]"
            comment += ".col_vec"
        args.append(f"\n        {nm}: {typ},  # {comment}")

    kittens_constant_name_line = ""
    if kittens_constant_name:
        kittens_constant_name_line = (
            f'\n    kittens_constant_name = "{kittens_constant_name}"'
        )
    prefix = "".join(p + "\n        " for p in prefix_lines)

    _def = f"""@instr
class {name}({base_name}):{kittens_constant_name_line}
    kittens_op_name = \"{kittens_op_name}\"
    valid_num_types = {valid_num_types}

    def behavior(
        rows: size,
        cols: size,{''.join(args)}
    ):
        {prefix}for r in seq(0, rows):
            for c in seq(0, cols):
                {body_stmt}
"""

    _all.append(name)
    _all_comments.append(str(body_stmt))
    _instr_defs.append(_def)


# Tile copy with optional type/precision conversion.
gen_instr(
    "cuda_tk_tile_copy",
    "basic_unary_tile_op",
    "copy",
    "dst[r, c] = src[r, c]",
    ("dst", "src"),
    valid_num_types="cuda_tk_valid_num_types_all_pairs",
)


# 0-ary ops: fill constant, make causal, make causal transpose
for name, value in (
    ("zero", "0"),
    ("one", "1"),
    ("pos_infty", "inf"),
    ("neg_infty", "-inf"),
):
    gen_instr(
        f"cuda_tk_tile_{name}",
        "basic_0ary_tile_op",
        name,
        f"dst[r, c] = {value}",
        ("dst",),
    )
    # TODO kittens_constant_name
    gen_instr(
        f"cuda_tk_make_causal_{name}",
        "basic_make_causal_op",
        "make_causal",
        f"if r < c:\n                    dst[r, c] = {value}",
        ("dst",),
        kittens_constant_name=name,
    )
    gen_instr(
        f"cuda_tk_make_causal_t_{name}",
        "basic_make_causal_op",
        "make_causal_t",
        f"if r > c:\n                    dst[r, c] = {value}",
        ("dst",),
        kittens_constant_name=name,
    )


for nm in ("pos_inf", "neg_inf"):
    _all.append(f"cuda_tk_tile_{nm}")
    _all_comments.append("For consistency with exo.inf")
    _instr_defs.append(f"cuda_tk_tile_{nm} = cuda_tk_tile_{nm}ty")
    _all.append(f"cuda_tk_make_causal_{nm}")
    _all_comments.append("For consistency with exo.inf")
    _instr_defs.append(f"cuda_tk_make_causal_{nm} = cuda_tk_make_causal_{nm}ty")
    _all.append(f"cuda_tk_make_causal_t_{nm}")
    _all_comments.append("For consistency with exo.inf")
    _instr_defs.append(f"cuda_tk_make_causal_t_{nm} = cuda_tk_make_causal_t_{nm}ty")


# Unary tile ops
unary_name_externs = [
    ("exp", "expf"),
    ("exp2", "exp2f"),
    ("log", "logf"),
    ("log2", "log2f"),
    ("abs", "fabsf"),
    ("relu", "relu"),
]
for name, extern in unary_name_externs:
    gen_instr(
        f"cuda_tk_tile_{name}",
        "basic_unary_tile_op",
        name,
        f"dst[r, c] = {extern}(src[r, c])",
        ("dst", "src"),
    )


# Binary tile ops, multiple forms
# dst = lhs op rhs
# dst = dst op src
# dst = src op dst
# dst += src
binary_name_stmt = [
    ("max", "{dst}[r, c] = fmaxf({lhs}[r, c], {rhs}[r, c])"),
    ("min", "{dst}[r, c] = fminf({lhs}[r, c], {rhs}[r, c])"),
    ("add", "{dst}[r, c] = {lhs}[r, c] + {rhs}[r, c]"),
    ("sub", "{dst}[r, c] = {lhs}[r, c] - {rhs}[r, c]"),
    ("mul", "{dst}[r, c] = {lhs}[r, c] * {rhs}[r, c]"),
    ("div", "{dst}[r, c] = {lhs}[r, c] / {rhs}[r, c]"),
]

for name, stmt_fmt in binary_name_stmt:
    gen_instr(
        f"cuda_tk_tile_{name}",
        "basic_binary_tile_op",
        name,
        stmt_fmt.format(dst="dst", lhs="lhs", rhs="rhs"),
        ("dst", "lhs", "rhs"),
    )
    if name == "add":
        gen_instr(
            f"cuda_tk_tile_{name}_reduce",
            "basic_binary_lhs_tile_op",
            name,
            "dst[r, c] += src[r, c]",
            ("dst", "src"),
        )
    gen_instr(
        f"cuda_tk_tile_{name}_lhs",
        "basic_binary_lhs_tile_op",
        name,
        stmt_fmt.format(dst="dst", lhs="dst", rhs="src"),
        ("dst", "src"),
    )
    gen_instr(
        f"cuda_tk_tile_{name}_rhs",
        "basic_binary_rhs_tile_op",
        name,
        stmt_fmt.format(dst="dst", lhs="src", rhs="dst"),
        ("src", "dst"),
    )


# Tile -> vec reductions
reduce_name_stmt_identity = [
    ("max", "dst[{axis}] = fmaxf(dst[{axis}], src[r, c])", "-inf"),
    ("min", "dst[{axis}] = fminf(dst[{axis}], src[r, c])", "inf"),
    ("sum", "dst[{axis}] += src[r, c]", "0"),
    ("prod", "dst[{axis}] = dst[{axis}] * src[r, c]", "1"),
]

for name, stmt_fmt, identity in reduce_name_stmt_identity:
    # Reduce each row -> get a column vector
    gen_instr(
        f"cuda_tk_row_{name}",
        "basic_row_reduce_op",
        f"row_{name}",
        stmt_fmt.format(axis="r"),
        ("dst", "src"),
        col_vec_names=("dst",),
        prefix_lines=(
            "for r in seq(0, rows):",
            f"    dst[r] = {identity}",
        ),
    )

    # Reduce each column -> get a row vector
    gen_instr(
        f"cuda_tk_col_{name}",
        "basic_col_reduce_op",
        f"col_{name}",
        stmt_fmt.format(axis="c"),
        ("dst", "src"),
        row_vec_names=("dst",),
        prefix_lines=(
            "for c in seq(0, cols):",
            f"    dst[c] = {identity}",
        ),
    )


# Vec -> tile
broadcast_name_stmt = [
    ("broadcast", "dst[r, c] = src[{axis}]"),
    ("add", "dst[r, c] += src[{axis}]"),
    ("sub", "dst[r, c] = dst[r, c] - src[{axis}]"),
    ("mul", "dst[r, c] = dst[r, c] * src[{axis}]"),
    ("div", "dst[r, c] = dst[r, c] / src[{axis}]"),
]

for name, stmt_fmt in broadcast_name_stmt:
    gen_instr(
        f"cuda_tk_{name}_row",
        "basic_broadcast_row_op",
        f"{name}_row",
        stmt_fmt.format(axis="r"),
        ("dst", "src"),
        col_vec_names=("src",),
    )
    gen_instr(
        f"cuda_tk_{name}_col",
        "basic_broadcast_col_op",
        f"{name}_col",
        stmt_fmt.format(axis="c"),
        ("dst", "src"),
        row_vec_names=("src",),
    )


#############################################################################
# Finalize file contents
#############################################################################

assert len(_all) == len(_all_comments)


all_lines = []
for nm, comment in zip(_all, _all_comments):
    comment = " ".join(comment.split())
    nm_repr = '"' + nm + '",'
    all_lines.append("    " + nm_repr + " " * (40 - len(nm_repr)) + "# " + comment)
all_lines_joined = "\n".join(all_lines)


write_chunk(
    f"""__all__ = [
{all_lines_joined}
]"""
)

for i, _def in enumerate(_instr_defs):
    variant_comment = f"# Tile op {i+1}/{len(_instr_defs)}\n"
    write_chunk(variant_comment + _def)


f.write("# End of file. Prevent black newline reformatting.\n")
f.close()
