# fmt: off

######################################################################
# Autogenerated by gen_tk_shared_to_register.py; do not hand-edit!!! #
######################################################################
from __future__ import annotations
from exo.API import instr
from exo.scalars import ScalarInfo

from .tk_shared_to_register_impl import (
    make_tk_load_rs_base,
    make_tk_store_rs_base,
    cuda_tk_rs_instr_advice_impl,
    CudaTkRsInstrAdvice,
)

_load_rs_instr_dict = {}
_store_rs_instr_dict = {}

__all__ = []

def cuda_tk_load_rs_advice(
    size0: int,
    size1: int, *,
    dst: ScalarInfo,
    src: ScalarInfo,
    swizzle: int
) -> CudaTkRsInstrAdvice:
    return cuda_tk_rs_instr_advice_impl(
        size0,
        size1,
        dst,
        src,
        swizzle,
        _load_rs_instr_dict,
        False,
    )

def cuda_tk_store_rs_advice(
    size0: int,
    size1: int, *,
    dst: ScalarInfo,
    src: ScalarInfo,
    swizzle: int
) -> CudaTkRsInstrAdvice:
    return cuda_tk_rs_instr_advice_impl(
        size0,
        size1,
        dst,
        src,
        swizzle,
        _store_rs_instr_dict,
        True,
    )

__all__.append("cuda_tk_load_rs_advice")
__all__.append("cuda_tk_store_rs_advice")
__all__.append("CudaTkRsInstrAdvice")



######################################################################
# Autogenerated by gen_tk_shared_to_register.py; do not hand-edit!!! #
######################################################################
@instr
class cuda_tk_load_rs_inner_cols_8(make_tk_load_rs_base(8)):
    """Warp copies 2D [rows, outer_cols * 8] RMEM tile to SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 8] tile,
    with RMEM[r, c] mapped to SMEM[c / 8, r, c % 8].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][rows, 8 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
        src: [R][outer_cols, rows, 8],  # @ Sm90_SmemSwizzled(8 * sizeof(R))
    ):
        assert stride(src, 1) == 8
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 8):
                    dst[row, outer_col * 8 + inner_col] = src[outer_col, row, inner_col]

@instr
class cuda_tk_store_rs_inner_cols_8(make_tk_store_rs_base(8)):
    """Warp copies 2D [rows, outer_cols * 8] RMEM tile from SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 8] tile,
    with RMEM[r, c] mapped to SMEM[c / 8, r, c % 8].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][outer_cols, rows, 8],  # @ Sm90_SmemSwizzled(8 * sizeof(R))
        src: [R][rows, 8 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
    ):
        assert stride(dst, 1) == 8
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 8):
                    dst[outer_col, row, inner_col] = src[row, outer_col * 8 + inner_col]

__all__.append("cuda_tk_load_rs_inner_cols_8")
__all__.append("cuda_tk_store_rs_inner_cols_8")
_load_rs_instr_dict[8] = cuda_tk_load_rs_inner_cols_8
_store_rs_instr_dict[8] = cuda_tk_store_rs_inner_cols_8


######################################################################
# Autogenerated by gen_tk_shared_to_register.py; do not hand-edit!!! #
######################################################################
@instr
class cuda_tk_load_rs_inner_cols_16(make_tk_load_rs_base(16)):
    """Warp copies 2D [rows, outer_cols * 16] RMEM tile to SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 16] tile,
    with RMEM[r, c] mapped to SMEM[c / 16, r, c % 16].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][rows, 16 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
        src: [R][outer_cols, rows, 16],  # @ Sm90_SmemSwizzled(16 * sizeof(R))
    ):
        assert stride(src, 1) == 16
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 16):
                    dst[row, outer_col * 16 + inner_col] = src[outer_col, row, inner_col]

@instr
class cuda_tk_store_rs_inner_cols_16(make_tk_store_rs_base(16)):
    """Warp copies 2D [rows, outer_cols * 16] RMEM tile from SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 16] tile,
    with RMEM[r, c] mapped to SMEM[c / 16, r, c % 16].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][outer_cols, rows, 16],  # @ Sm90_SmemSwizzled(16 * sizeof(R))
        src: [R][rows, 16 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
    ):
        assert stride(dst, 1) == 16
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 16):
                    dst[outer_col, row, inner_col] = src[row, outer_col * 16 + inner_col]

__all__.append("cuda_tk_load_rs_inner_cols_16")
__all__.append("cuda_tk_store_rs_inner_cols_16")
_load_rs_instr_dict[16] = cuda_tk_load_rs_inner_cols_16
_store_rs_instr_dict[16] = cuda_tk_store_rs_inner_cols_16


######################################################################
# Autogenerated by gen_tk_shared_to_register.py; do not hand-edit!!! #
######################################################################
@instr
class cuda_tk_load_rs_inner_cols_32(make_tk_load_rs_base(32)):
    """Warp copies 2D [rows, outer_cols * 32] RMEM tile to SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 32] tile,
    with RMEM[r, c] mapped to SMEM[c / 32, r, c % 32].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][rows, 32 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
        src: [R][outer_cols, rows, 32],  # @ Sm90_SmemSwizzled(32 * sizeof(R))
    ):
        assert stride(src, 1) == 32
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 32):
                    dst[row, outer_col * 32 + inner_col] = src[outer_col, row, inner_col]

@instr
class cuda_tk_store_rs_inner_cols_32(make_tk_store_rs_base(32)):
    """Warp copies 2D [rows, outer_cols * 32] RMEM tile from SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 32] tile,
    with RMEM[r, c] mapped to SMEM[c / 32, r, c % 32].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][outer_cols, rows, 32],  # @ Sm90_SmemSwizzled(32 * sizeof(R))
        src: [R][rows, 32 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
    ):
        assert stride(dst, 1) == 32
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 32):
                    dst[outer_col, row, inner_col] = src[row, outer_col * 32 + inner_col]

__all__.append("cuda_tk_load_rs_inner_cols_32")
__all__.append("cuda_tk_store_rs_inner_cols_32")
_load_rs_instr_dict[32] = cuda_tk_load_rs_inner_cols_32
_store_rs_instr_dict[32] = cuda_tk_store_rs_inner_cols_32


######################################################################
# Autogenerated by gen_tk_shared_to_register.py; do not hand-edit!!! #
######################################################################
@instr
class cuda_tk_load_rs_inner_cols_64(make_tk_load_rs_base(64)):
    """Warp copies 2D [rows, outer_cols * 64] RMEM tile to SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 64] tile,
    with RMEM[r, c] mapped to SMEM[c / 64, r, c % 64].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][rows, 64 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
        src: [R][outer_cols, rows, 64],  # @ Sm90_SmemSwizzled(64 * sizeof(R))
    ):
        assert stride(src, 1) == 64
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 64):
                    dst[row, outer_col * 64 + inner_col] = src[outer_col, row, inner_col]

@instr
class cuda_tk_store_rs_inner_cols_64(make_tk_store_rs_base(64)):
    """Warp copies 2D [rows, outer_cols * 64] RMEM tile from SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 64] tile,
    with RMEM[r, c] mapped to SMEM[c / 64, r, c % 64].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][outer_cols, rows, 64],  # @ Sm90_SmemSwizzled(64 * sizeof(R))
        src: [R][rows, 64 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
    ):
        assert stride(dst, 1) == 64
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 64):
                    dst[outer_col, row, inner_col] = src[row, outer_col * 64 + inner_col]

__all__.append("cuda_tk_load_rs_inner_cols_64")
__all__.append("cuda_tk_store_rs_inner_cols_64")
_load_rs_instr_dict[64] = cuda_tk_load_rs_inner_cols_64
_store_rs_instr_dict[64] = cuda_tk_store_rs_inner_cols_64


######################################################################
# Autogenerated by gen_tk_shared_to_register.py; do not hand-edit!!! #
######################################################################
@instr
class cuda_tk_load_rs_inner_cols_128(make_tk_load_rs_base(128)):
    """Warp copies 2D [rows, outer_cols * 128] RMEM tile to SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 128] tile,
    with RMEM[r, c] mapped to SMEM[c / 128, r, c % 128].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][rows, 128 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
        src: [R][outer_cols, rows, 128],  # @ Sm90_SmemSwizzled(128 * sizeof(R))
    ):
        assert stride(src, 1) == 128
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 128):
                    dst[row, outer_col * 128 + inner_col] = src[outer_col, row, inner_col]

@instr
class cuda_tk_store_rs_inner_cols_128(make_tk_store_rs_base(128)):
    """Warp copies 2D [rows, outer_cols * 128] RMEM tile from SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, 128] tile,
    with RMEM[r, c] mapped to SMEM[c / 128, r, c % 128].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][outer_cols, rows, 128],  # @ Sm90_SmemSwizzled(128 * sizeof(R))
        src: [R][rows, 128 * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
    ):
        assert stride(dst, 1) == 128
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, 128):
                    dst[outer_col, row, inner_col] = src[row, outer_col * 128 + inner_col]

__all__.append("cuda_tk_load_rs_inner_cols_128")
__all__.append("cuda_tk_store_rs_inner_cols_128")
_load_rs_instr_dict[128] = cuda_tk_load_rs_inner_cols_128
_store_rs_instr_dict[128] = cuda_tk_store_rs_inner_cols_128

# End of file. Prevent black newline reformatting.
