# fmt: off

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
from __future__ import annotations
from exo.API import instr
from exo.scalars import ScalarInfo, inf

from exo.libs.externs import fabsf, fminf, fmaxf, relu, expf, exp2f, logf, log2f

from .tk_tile_ops_impl import (
    basic_0ary_tile_op,
    basic_make_causal_op,
    basic_unary_tile_op,
    basic_binary_tile_op,
    basic_binary_lhs_tile_op,
    basic_binary_rhs_tile_op,
    basic_row_reduce_op,
    basic_col_reduce_op,
    basic_broadcast_row_op,
    basic_broadcast_col_op,
)



#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
__all__ = [
    "cuda_tk_tile_zero",                    # dst[r, c] = 0
    "cuda_tk_make_causal_zero",             # if r < c: dst[r, c] = 0
    "cuda_tk_make_causal_t_zero",           # if r > c: dst[r, c] = 0
    "cuda_tk_tile_one",                     # dst[r, c] = 1
    "cuda_tk_make_causal_one",              # if r < c: dst[r, c] = 1
    "cuda_tk_make_causal_t_one",            # if r > c: dst[r, c] = 1
    "cuda_tk_tile_pos_infty",               # dst[r, c] = inf
    "cuda_tk_make_causal_pos_infty",        # if r < c: dst[r, c] = inf
    "cuda_tk_make_causal_t_pos_infty",      # if r > c: dst[r, c] = inf
    "cuda_tk_tile_neg_infty",               # dst[r, c] = -inf
    "cuda_tk_make_causal_neg_infty",        # if r < c: dst[r, c] = -inf
    "cuda_tk_make_causal_t_neg_infty",      # if r > c: dst[r, c] = -inf
    "cuda_tk_tile_pos_inf",                 # For consistency with exo.inf
    "cuda_tk_make_causal_pos_inf",          # For consistency with exo.inf
    "cuda_tk_make_causal_t_pos_inf",        # For consistency with exo.inf
    "cuda_tk_tile_neg_inf",                 # For consistency with exo.inf
    "cuda_tk_make_causal_neg_inf",          # For consistency with exo.inf
    "cuda_tk_make_causal_t_neg_inf",        # For consistency with exo.inf
    "cuda_tk_tile_exp",                     # dst[r, c] = expf(src[r, c])
    "cuda_tk_tile_exp2",                    # dst[r, c] = exp2f(src[r, c])
    "cuda_tk_tile_log",                     # dst[r, c] = logf(src[r, c])
    "cuda_tk_tile_log2",                    # dst[r, c] = log2f(src[r, c])
    "cuda_tk_tile_abs",                     # dst[r, c] = fabsf(src[r, c])
    "cuda_tk_tile_relu",                    # dst[r, c] = relu(src[r, c])
    "cuda_tk_tile_max",                     # dst[r, c] = fmaxf(lhs[r, c], rhs[r, c])
    "cuda_tk_tile_max_lhs",                 # dst[r, c] = fmaxf(dst[r, c], src[r, c])
    "cuda_tk_tile_max_rhs",                 # dst[r, c] = fmaxf(src[r, c], dst[r, c])
    "cuda_tk_tile_min",                     # dst[r, c] = fminf(lhs[r, c], rhs[r, c])
    "cuda_tk_tile_min_lhs",                 # dst[r, c] = fminf(dst[r, c], src[r, c])
    "cuda_tk_tile_min_rhs",                 # dst[r, c] = fminf(src[r, c], dst[r, c])
    "cuda_tk_tile_add",                     # dst[r, c] = lhs[r, c] + rhs[r, c]
    "cuda_tk_tile_add_reduce",              # dst[r, c] += src[r, c]
    "cuda_tk_tile_add_lhs",                 # dst[r, c] = dst[r, c] + src[r, c]
    "cuda_tk_tile_add_rhs",                 # dst[r, c] = src[r, c] + dst[r, c]
    "cuda_tk_tile_sub",                     # dst[r, c] = lhs[r, c] - rhs[r, c]
    "cuda_tk_tile_sub_lhs",                 # dst[r, c] = dst[r, c] - src[r, c]
    "cuda_tk_tile_sub_rhs",                 # dst[r, c] = src[r, c] - dst[r, c]
    "cuda_tk_tile_mul",                     # dst[r, c] = lhs[r, c] * rhs[r, c]
    "cuda_tk_tile_mul_lhs",                 # dst[r, c] = dst[r, c] * src[r, c]
    "cuda_tk_tile_mul_rhs",                 # dst[r, c] = src[r, c] * dst[r, c]
    "cuda_tk_tile_div",                     # dst[r, c] = lhs[r, c] / rhs[r, c]
    "cuda_tk_tile_div_lhs",                 # dst[r, c] = dst[r, c] / src[r, c]
    "cuda_tk_tile_div_rhs",                 # dst[r, c] = src[r, c] / dst[r, c]
    "cuda_tk_row_max",                      # dst[r] = fmaxf(dst[r], src[r, c])
    "cuda_tk_col_max",                      # dst[c] = fmaxf(dst[c], src[r, c])
    "cuda_tk_row_min",                      # dst[r] = fminf(dst[r], src[r, c])
    "cuda_tk_col_min",                      # dst[c] = fminf(dst[c], src[r, c])
    "cuda_tk_row_sum",                      # dst[r] += src[r, c]
    "cuda_tk_col_sum",                      # dst[c] += src[r, c]
    "cuda_tk_row_prod",                     # dst[r] = dst[r] * src[r, c]
    "cuda_tk_col_prod",                     # dst[c] = dst[c] * src[r, c]
    "cuda_tk_broadcast_row",                # dst[r, c] = src[c]
    "cuda_tk_broadcast_col",                # dst[r, c] = src[r]
    "cuda_tk_add_row",                      # dst[r, c] += src[c]
    "cuda_tk_add_col",                      # dst[r, c] += src[r]
    "cuda_tk_sub_row",                      # dst[r, c] = dst[r, c] - src[c]
    "cuda_tk_sub_col",                      # dst[r, c] = dst[r, c] - src[r]
    "cuda_tk_mul_row",                      # dst[r, c] = dst[r, c] * src[c]
    "cuda_tk_mul_col",                      # dst[r, c] = dst[r, c] * src[r]
    "cuda_tk_div_row",                      # dst[r, c] = dst[r, c] / src[c]
    "cuda_tk_div_col",                      # dst[r, c] = dst[r, c] / src[r]
]

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 1/61
@instr
class cuda_tk_tile_zero(basic_0ary_tile_op):
    kittens_op_name = "zero"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = 0


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 2/61
@instr
class cuda_tk_make_causal_zero(basic_make_causal_op):
    kittens_constant_name = "zero"
    kittens_op_name = "make_causal"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r < c:
                    dst[r, c] = 0


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 3/61
@instr
class cuda_tk_make_causal_t_zero(basic_make_causal_op):
    kittens_constant_name = "zero"
    kittens_op_name = "make_causal_t"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r > c:
                    dst[r, c] = 0


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 4/61
@instr
class cuda_tk_tile_one(basic_0ary_tile_op):
    kittens_op_name = "one"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = 1


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 5/61
@instr
class cuda_tk_make_causal_one(basic_make_causal_op):
    kittens_constant_name = "one"
    kittens_op_name = "make_causal"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r < c:
                    dst[r, c] = 1


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 6/61
@instr
class cuda_tk_make_causal_t_one(basic_make_causal_op):
    kittens_constant_name = "one"
    kittens_op_name = "make_causal_t"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r > c:
                    dst[r, c] = 1


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 7/61
@instr
class cuda_tk_tile_pos_infty(basic_0ary_tile_op):
    kittens_op_name = "pos_infty"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 8/61
@instr
class cuda_tk_make_causal_pos_infty(basic_make_causal_op):
    kittens_constant_name = "pos_infty"
    kittens_op_name = "make_causal"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r < c:
                    dst[r, c] = inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 9/61
@instr
class cuda_tk_make_causal_t_pos_infty(basic_make_causal_op):
    kittens_constant_name = "pos_infty"
    kittens_op_name = "make_causal_t"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r > c:
                    dst[r, c] = inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 10/61
@instr
class cuda_tk_tile_neg_infty(basic_0ary_tile_op):
    kittens_op_name = "neg_infty"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = -inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 11/61
@instr
class cuda_tk_make_causal_neg_infty(basic_make_causal_op):
    kittens_constant_name = "neg_infty"
    kittens_op_name = "make_causal"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r < c:
                    dst[r, c] = -inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 12/61
@instr
class cuda_tk_make_causal_t_neg_infty(basic_make_causal_op):
    kittens_constant_name = "neg_infty"
    kittens_op_name = "make_causal_t"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r > c:
                    dst[r, c] = -inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 13/61
cuda_tk_tile_pos_inf = cuda_tk_tile_pos_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 14/61
cuda_tk_make_causal_pos_inf = cuda_tk_make_causal_pos_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 15/61
cuda_tk_make_causal_t_pos_inf = cuda_tk_make_causal_t_pos_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 16/61
cuda_tk_tile_neg_inf = cuda_tk_tile_neg_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 17/61
cuda_tk_make_causal_neg_inf = cuda_tk_make_causal_neg_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 18/61
cuda_tk_make_causal_t_neg_inf = cuda_tk_make_causal_t_neg_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 19/61
@instr
class cuda_tk_tile_exp(basic_unary_tile_op):
    kittens_op_name = "exp"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = expf(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 20/61
@instr
class cuda_tk_tile_exp2(basic_unary_tile_op):
    kittens_op_name = "exp2"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = exp2f(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 21/61
@instr
class cuda_tk_tile_log(basic_unary_tile_op):
    kittens_op_name = "log"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = logf(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 22/61
@instr
class cuda_tk_tile_log2(basic_unary_tile_op):
    kittens_op_name = "log2"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = log2f(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 23/61
@instr
class cuda_tk_tile_abs(basic_unary_tile_op):
    kittens_op_name = "abs"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fabsf(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 24/61
@instr
class cuda_tk_tile_relu(basic_unary_tile_op):
    kittens_op_name = "relu"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = relu(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 25/61
@instr
class cuda_tk_tile_max(basic_binary_tile_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(lhs[r, c], rhs[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 26/61
@instr
class cuda_tk_tile_max_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(dst[r, c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 27/61
@instr
class cuda_tk_tile_max_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(src[r, c], dst[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 28/61
@instr
class cuda_tk_tile_min(basic_binary_tile_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(lhs[r, c], rhs[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 29/61
@instr
class cuda_tk_tile_min_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(dst[r, c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 30/61
@instr
class cuda_tk_tile_min_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(src[r, c], dst[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 31/61
@instr
class cuda_tk_tile_add(basic_binary_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] + rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 32/61
@instr
class cuda_tk_tile_add_reduce(basic_binary_lhs_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] += src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 33/61
@instr
class cuda_tk_tile_add_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] + src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 34/61
@instr
class cuda_tk_tile_add_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] + dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 35/61
@instr
class cuda_tk_tile_sub(basic_binary_tile_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] - rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 36/61
@instr
class cuda_tk_tile_sub_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] - src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 37/61
@instr
class cuda_tk_tile_sub_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] - dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 38/61
@instr
class cuda_tk_tile_mul(basic_binary_tile_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] * rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 39/61
@instr
class cuda_tk_tile_mul_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] * src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 40/61
@instr
class cuda_tk_tile_mul_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] * dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 41/61
@instr
class cuda_tk_tile_div(basic_binary_tile_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] / rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 42/61
@instr
class cuda_tk_tile_div_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] / src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 43/61
@instr
class cuda_tk_tile_div_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] / dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 44/61
@instr
class cuda_tk_row_max(basic_row_reduce_op):
    kittens_op_name = "row_max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            dst[r] = -inf
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] = fmaxf(dst[r], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 45/61
@instr
class cuda_tk_col_max(basic_col_reduce_op):
    kittens_op_name = "col_max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for c in seq(0, cols):
            dst[c] = -inf
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] = fmaxf(dst[c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 46/61
@instr
class cuda_tk_row_min(basic_row_reduce_op):
    kittens_op_name = "row_min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            dst[r] = inf
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] = fminf(dst[r], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 47/61
@instr
class cuda_tk_col_min(basic_col_reduce_op):
    kittens_op_name = "col_min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for c in seq(0, cols):
            dst[c] = inf
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] = fminf(dst[c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 48/61
@instr
class cuda_tk_row_sum(basic_row_reduce_op):
    kittens_op_name = "row_sum"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            dst[r] = 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] += src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 49/61
@instr
class cuda_tk_col_sum(basic_col_reduce_op):
    kittens_op_name = "col_sum"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for c in seq(0, cols):
            dst[c] = 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] += src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 50/61
@instr
class cuda_tk_row_prod(basic_row_reduce_op):
    kittens_op_name = "row_prod"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            dst[r] = 1
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] = dst[r] * src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 51/61
@instr
class cuda_tk_col_prod(basic_col_reduce_op):
    kittens_op_name = "col_prod"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for c in seq(0, cols):
            dst[c] = 1
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] = dst[c] * src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 52/61
@instr
class cuda_tk_broadcast_row(basic_broadcast_row_op):
    kittens_op_name = "broadcast_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 53/61
@instr
class cuda_tk_broadcast_col(basic_broadcast_col_op):
    kittens_op_name = "broadcast_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 54/61
@instr
class cuda_tk_add_row(basic_broadcast_row_op):
    kittens_op_name = "add_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] += src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 55/61
@instr
class cuda_tk_add_col(basic_broadcast_col_op):
    kittens_op_name = "add_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] += src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 56/61
@instr
class cuda_tk_sub_row(basic_broadcast_row_op):
    kittens_op_name = "sub_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] - src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 57/61
@instr
class cuda_tk_sub_col(basic_broadcast_col_op):
    kittens_op_name = "sub_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] - src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 58/61
@instr
class cuda_tk_mul_row(basic_broadcast_row_op):
    kittens_op_name = "mul_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] * src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 59/61
@instr
class cuda_tk_mul_col(basic_broadcast_col_op):
    kittens_op_name = "mul_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] * src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 60/61
@instr
class cuda_tk_div_row(basic_broadcast_row_op):
    kittens_op_name = "div_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] / src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 61/61
@instr
class cuda_tk_div_col(basic_broadcast_col_op):
    kittens_op_name = "div_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,
        cols: size,
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] / src[r]

# End of file. Prevent black newline reformatting.
