# fmt: off

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
from __future__ import annotations
from exo.API import instr
from exo.scalars import ScalarInfo, inf, bf16, f16, f32

from exo.libs.externs import fabsf, fminf, fmaxf, relu, expf, exp2f, logf, log2f

from .tk_types import *

from .tk_tile_ops_impl import (
    basic_0ary_tile_op,
    basic_make_causal_op,
    basic_unary_tile_op,
    basic_binary_3op_tile_op,
    basic_binary_lhs_tile_op,
    basic_binary_rhs_tile_op,
    basic_binary_3op_tile_scalar_op,
    basic_binary_lhs_tile_scalar_op,
    basic_row_reduce_op,
    basic_col_reduce_op,
    basic_broadcast_row_op,
    basic_broadcast_col_op,
)

from ..cuda import CudaBasicDeviceVisible



#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
__all__ = [
    "cuda_tk_tile_copy",                    # dst[r, c] = src[r, c]
    "cuda_tk_tile_zero",                    # dst[r, c] = 0
    "cuda_tk_make_causal_zero",             # if r - row_offset < c - col_offset: dst[r, c] = 0
    "cuda_tk_make_causal_t_zero",           # if r - row_offset > c - col_offset: dst[r, c] = 0
    "cuda_tk_tile_one",                     # dst[r, c] = 1
    "cuda_tk_make_causal_one",              # if r - row_offset < c - col_offset: dst[r, c] = 1
    "cuda_tk_make_causal_t_one",            # if r - row_offset > c - col_offset: dst[r, c] = 1
    "cuda_tk_tile_pos_infty",               # dst[r, c] = inf
    "cuda_tk_make_causal_pos_infty",        # if r - row_offset < c - col_offset: dst[r, c] = inf
    "cuda_tk_make_causal_t_pos_infty",      # if r - row_offset > c - col_offset: dst[r, c] = inf
    "cuda_tk_tile_neg_infty",               # dst[r, c] = -inf
    "cuda_tk_make_causal_neg_infty",        # if r - row_offset < c - col_offset: dst[r, c] = -inf
    "cuda_tk_make_causal_t_neg_infty",      # if r - row_offset > c - col_offset: dst[r, c] = -inf
    "cuda_tk_tile_pos_inf",                 # For consistency with exo.inf
    "cuda_tk_make_causal_pos_inf",          # For consistency with exo.inf
    "cuda_tk_make_causal_t_pos_inf",        # For consistency with exo.inf
    "cuda_tk_tile_neg_inf",                 # For consistency with exo.inf
    "cuda_tk_make_causal_neg_inf",          # For consistency with exo.inf
    "cuda_tk_make_causal_t_neg_inf",        # For consistency with exo.inf
    "cuda_tk_tile_exp",                     # dst[r, c] = expf(src[r, c])
    "cuda_tk_tile_exp2",                    # dst[r, c] = exp2f(src[r, c])
    "cuda_tk_tile_log",                     # dst[r, c] = logf(src[r, c])
    "cuda_tk_tile_log2",                    # dst[r, c] = log2f(src[r, c])
    "cuda_tk_tile_abs",                     # dst[r, c] = fabsf(src[r, c])
    "cuda_tk_tile_relu",                    # dst[r, c] = relu(src[r, c])
    "cuda_tk_tile_max_3op",                 # dst[r, c] = fmaxf(lhs[r, c], rhs[r, c])
    "cuda_tk_tile_max_3op_scalar",          # dst[r, c] = fmaxf(lhs[r, c], rhs)
    "cuda_tk_tile_max_lhs",                 # dst[r, c] = fmaxf(dst[r, c], src[r, c])
    "cuda_tk_tile_max_lhs_scalar",          # dst[r, c] = fmaxf(dst[r, c], src)
    "cuda_tk_tile_max_rhs",                 # dst[r, c] = fmaxf(src[r, c], dst[r, c])
    "cuda_tk_tile_min_3op",                 # dst[r, c] = fminf(lhs[r, c], rhs[r, c])
    "cuda_tk_tile_min_3op_scalar",          # dst[r, c] = fminf(lhs[r, c], rhs)
    "cuda_tk_tile_min_lhs",                 # dst[r, c] = fminf(dst[r, c], src[r, c])
    "cuda_tk_tile_min_lhs_scalar",          # dst[r, c] = fminf(dst[r, c], src)
    "cuda_tk_tile_min_rhs",                 # dst[r, c] = fminf(src[r, c], dst[r, c])
    "cuda_tk_tile_add_3op",                 # dst[r, c] = lhs[r, c] + rhs[r, c]
    "cuda_tk_tile_add_3op_scalar",          # dst[r, c] = lhs[r, c] + rhs
    "cuda_tk_tile_add_reduce",              # dst[r, c] += src[r, c]
    "cuda_tk_tile_add_reduce_scalar",       # dst[r, c] += src
    "cuda_tk_tile_add_lhs",                 # dst[r, c] = dst[r, c] + src[r, c]
    "cuda_tk_tile_add_lhs_scalar",          # dst[r, c] = dst[r, c] + src
    "cuda_tk_tile_add_rhs",                 # dst[r, c] = src[r, c] + dst[r, c]
    "cuda_tk_tile_sub_3op",                 # dst[r, c] = lhs[r, c] - rhs[r, c]
    "cuda_tk_tile_sub_3op_scalar",          # dst[r, c] = lhs[r, c] - rhs
    "cuda_tk_tile_sub_lhs",                 # dst[r, c] = dst[r, c] - src[r, c]
    "cuda_tk_tile_sub_lhs_scalar",          # dst[r, c] = dst[r, c] - src
    "cuda_tk_tile_sub_rhs",                 # dst[r, c] = src[r, c] - dst[r, c]
    "cuda_tk_tile_mul_3op",                 # dst[r, c] = lhs[r, c] * rhs[r, c]
    "cuda_tk_tile_mul_3op_scalar",          # dst[r, c] = lhs[r, c] * rhs
    "cuda_tk_tile_mul_lhs",                 # dst[r, c] = dst[r, c] * src[r, c]
    "cuda_tk_tile_mul_lhs_scalar",          # dst[r, c] = dst[r, c] * src
    "cuda_tk_tile_mul_rhs",                 # dst[r, c] = src[r, c] * dst[r, c]
    "cuda_tk_tile_div_3op",                 # dst[r, c] = lhs[r, c] / rhs[r, c]
    "cuda_tk_tile_div_3op_scalar",          # dst[r, c] = lhs[r, c] / rhs
    "cuda_tk_tile_div_lhs",                 # dst[r, c] = dst[r, c] / src[r, c]
    "cuda_tk_tile_div_lhs_scalar",          # dst[r, c] = dst[r, c] / src
    "cuda_tk_tile_div_rhs",                 # dst[r, c] = src[r, c] / dst[r, c]
    "cuda_tk_row_max",                      # dst[r] = fmaxf(dst[r], src[r, c])
    "cuda_tk_col_max",                      # dst[c] = fmaxf(dst[c], src[r, c])
    "cuda_tk_row_min",                      # dst[r] = fminf(dst[r], src[r, c])
    "cuda_tk_col_min",                      # dst[c] = fminf(dst[c], src[r, c])
    "cuda_tk_row_sum",                      # dst[r] += src[r, c]
    "cuda_tk_col_sum",                      # dst[c] += src[r, c]
    "cuda_tk_row_prod",                     # dst[r] = dst[r] * src[r, c]
    "cuda_tk_col_prod",                     # dst[c] = dst[c] * src[r, c]
    "cuda_tk_broadcast_row",                # dst[r, c] = src[r]
    "cuda_tk_broadcast_col",                # dst[r, c] = src[c]
    "cuda_tk_add_row",                      # dst[r, c] += src[r]
    "cuda_tk_add_col",                      # dst[r, c] += src[c]
    "cuda_tk_sub_row",                      # dst[r, c] = dst[r, c] - src[r]
    "cuda_tk_sub_col",                      # dst[r, c] = dst[r, c] - src[c]
    "cuda_tk_mul_row",                      # dst[r, c] = dst[r, c] * src[r]
    "cuda_tk_mul_col",                      # dst[r, c] = dst[r, c] * src[c]
    "cuda_tk_div_row",                      # dst[r, c] = dst[r, c] / src[r]
    "cuda_tk_div_col",                      # dst[r, c] = dst[r, c] / src[c]
]

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 1/75
@instr
class cuda_tk_tile_copy(basic_unary_tile_op):
    kittens_op_name = "copy"
    valid_num_types = cuda_tk_valid_num_types_all_pairs

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 2/75
@instr
class cuda_tk_tile_zero(basic_0ary_tile_op):
    kittens_op_name = "zero"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = 0


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 3/75
@instr
class cuda_tk_make_causal_zero(basic_make_causal_op):
    kittens_constant_name = "zero"
    cmp_op = "<"
    kittens_op_name = "make_causal"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset < c - col_offset:
                    dst[r, c] = 0


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 4/75
@instr
class cuda_tk_make_causal_t_zero(basic_make_causal_op):
    kittens_constant_name = "zero"
    cmp_op = ">"
    kittens_op_name = "make_causal_t"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset > c - col_offset:
                    dst[r, c] = 0


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 5/75
@instr
class cuda_tk_tile_one(basic_0ary_tile_op):
    kittens_op_name = "one"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = 1


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 6/75
@instr
class cuda_tk_make_causal_one(basic_make_causal_op):
    kittens_constant_name = "one"
    cmp_op = "<"
    kittens_op_name = "make_causal"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset < c - col_offset:
                    dst[r, c] = 1


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 7/75
@instr
class cuda_tk_make_causal_t_one(basic_make_causal_op):
    kittens_constant_name = "one"
    cmp_op = ">"
    kittens_op_name = "make_causal_t"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset > c - col_offset:
                    dst[r, c] = 1


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 8/75
@instr
class cuda_tk_tile_pos_infty(basic_0ary_tile_op):
    kittens_op_name = "pos_infty"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 9/75
@instr
class cuda_tk_make_causal_pos_infty(basic_make_causal_op):
    kittens_constant_name = "pos_infty"
    cmp_op = "<"
    kittens_op_name = "make_causal"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset < c - col_offset:
                    dst[r, c] = inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 10/75
@instr
class cuda_tk_make_causal_t_pos_infty(basic_make_causal_op):
    kittens_constant_name = "pos_infty"
    cmp_op = ">"
    kittens_op_name = "make_causal_t"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset > c - col_offset:
                    dst[r, c] = inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 11/75
@instr
class cuda_tk_tile_neg_infty(basic_0ary_tile_op):
    kittens_op_name = "neg_infty"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = -inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 12/75
@instr
class cuda_tk_make_causal_neg_infty(basic_make_causal_op):
    kittens_constant_name = "neg_infty"
    cmp_op = "<"
    kittens_op_name = "make_causal"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset < c - col_offset:
                    dst[r, c] = -inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 13/75
@instr
class cuda_tk_make_causal_t_neg_infty(basic_make_causal_op):
    kittens_constant_name = "neg_infty"
    cmp_op = ">"
    kittens_op_name = "make_causal_t"
    valid_num_types = {(bf16,), (f16,), (f32,),}

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        row_offset: index,  # Runtime index (not template parameter)
        col_offset: index,  # Runtime index (not template parameter)
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        assert row_offset % 16 == 0
        assert col_offset % 16 == 0
        for r in seq(0, rows):
            for c in seq(0, cols):
                if r - row_offset > c - col_offset:
                    dst[r, c] = -inf


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 14/75
cuda_tk_tile_pos_inf = cuda_tk_tile_pos_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 15/75
cuda_tk_make_causal_pos_inf = cuda_tk_make_causal_pos_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 16/75
cuda_tk_make_causal_t_pos_inf = cuda_tk_make_causal_t_pos_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 17/75
cuda_tk_tile_neg_inf = cuda_tk_tile_neg_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 18/75
cuda_tk_make_causal_neg_inf = cuda_tk_make_causal_neg_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 19/75
cuda_tk_make_causal_t_neg_inf = cuda_tk_make_causal_t_neg_infty

#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 20/75
@instr
class cuda_tk_tile_exp(basic_unary_tile_op):
    kittens_op_name = "exp"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = expf(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 21/75
@instr
class cuda_tk_tile_exp2(basic_unary_tile_op):
    kittens_op_name = "exp2"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = exp2f(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 22/75
@instr
class cuda_tk_tile_log(basic_unary_tile_op):
    kittens_op_name = "log"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = logf(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 23/75
@instr
class cuda_tk_tile_log2(basic_unary_tile_op):
    kittens_op_name = "log2"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = log2f(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 24/75
@instr
class cuda_tk_tile_abs(basic_unary_tile_op):
    kittens_op_name = "abs"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fabsf(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 25/75
@instr
class cuda_tk_tile_relu(basic_unary_tile_op):
    kittens_op_name = "relu"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = relu(src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 26/75
@instr
class cuda_tk_tile_max_3op(basic_binary_3op_tile_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(lhs[r, c], rhs[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 27/75
@instr
class cuda_tk_tile_max_3op_scalar(basic_binary_3op_tile_scalar_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(lhs[r, c], rhs)


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 28/75
@instr
class cuda_tk_tile_max_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(dst[r, c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 29/75
@instr
class cuda_tk_tile_max_lhs_scalar(basic_binary_lhs_tile_scalar_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(dst[r, c], src)


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 30/75
@instr
class cuda_tk_tile_max_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fmaxf(src[r, c], dst[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 31/75
@instr
class cuda_tk_tile_min_3op(basic_binary_3op_tile_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(lhs[r, c], rhs[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 32/75
@instr
class cuda_tk_tile_min_3op_scalar(basic_binary_3op_tile_scalar_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(lhs[r, c], rhs)


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 33/75
@instr
class cuda_tk_tile_min_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(dst[r, c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 34/75
@instr
class cuda_tk_tile_min_lhs_scalar(basic_binary_lhs_tile_scalar_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(dst[r, c], src)


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 35/75
@instr
class cuda_tk_tile_min_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = fminf(src[r, c], dst[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 36/75
@instr
class cuda_tk_tile_add_3op(basic_binary_3op_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] + rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 37/75
@instr
class cuda_tk_tile_add_3op_scalar(basic_binary_3op_tile_scalar_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] + rhs


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 38/75
@instr
class cuda_tk_tile_add_reduce(basic_binary_lhs_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] += src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 39/75
@instr
class cuda_tk_tile_add_reduce_scalar(basic_binary_lhs_tile_scalar_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] += src


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 40/75
@instr
class cuda_tk_tile_add_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] + src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 41/75
@instr
class cuda_tk_tile_add_lhs_scalar(basic_binary_lhs_tile_scalar_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] + src


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 42/75
@instr
class cuda_tk_tile_add_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "add"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] + dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 43/75
@instr
class cuda_tk_tile_sub_3op(basic_binary_3op_tile_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] - rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 44/75
@instr
class cuda_tk_tile_sub_3op_scalar(basic_binary_3op_tile_scalar_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] - rhs


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 45/75
@instr
class cuda_tk_tile_sub_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] - src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 46/75
@instr
class cuda_tk_tile_sub_lhs_scalar(basic_binary_lhs_tile_scalar_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] - src


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 47/75
@instr
class cuda_tk_tile_sub_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "sub"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] - dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 48/75
@instr
class cuda_tk_tile_mul_3op(basic_binary_3op_tile_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] * rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 49/75
@instr
class cuda_tk_tile_mul_3op_scalar(basic_binary_3op_tile_scalar_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] * rhs


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 50/75
@instr
class cuda_tk_tile_mul_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] * src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 51/75
@instr
class cuda_tk_tile_mul_lhs_scalar(basic_binary_lhs_tile_scalar_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] * src


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 52/75
@instr
class cuda_tk_tile_mul_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "mul"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] * dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 53/75
@instr
class cuda_tk_tile_div_3op(basic_binary_3op_tile_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] / rhs[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 54/75
@instr
class cuda_tk_tile_div_3op_scalar(basic_binary_3op_tile_scalar_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        lhs: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        rhs: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = lhs[r, c] / rhs


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 55/75
@instr
class cuda_tk_tile_div_lhs(basic_binary_lhs_tile_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] / src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 56/75
@instr
class cuda_tk_tile_div_lhs_scalar(basic_binary_lhs_tile_scalar_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: R @ CudaBasicDeviceVisible,  # Often, CudaRmemUniform(32)
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] / src


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 57/75
@instr
class cuda_tk_tile_div_rhs(basic_binary_rhs_tile_op):
    kittens_op_name = "div"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r, c] / dst[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 58/75
@instr
class cuda_tk_row_max(basic_row_reduce_op):
    kittens_op_name = "row_max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] = fmaxf(dst[r], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 59/75
@instr
class cuda_tk_col_max(basic_col_reduce_op):
    kittens_op_name = "col_max"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] = fmaxf(dst[c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 60/75
@instr
class cuda_tk_row_min(basic_row_reduce_op):
    kittens_op_name = "row_min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] = fminf(dst[r], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 61/75
@instr
class cuda_tk_col_min(basic_col_reduce_op):
    kittens_op_name = "col_min"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] = fminf(dst[c], src[r, c])


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 62/75
@instr
class cuda_tk_row_sum(basic_row_reduce_op):
    kittens_op_name = "row_sum"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] += src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 63/75
@instr
class cuda_tk_col_sum(basic_col_reduce_op):
    kittens_op_name = "col_sum"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] += src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 64/75
@instr
class cuda_tk_row_prod(basic_row_reduce_op):
    kittens_op_name = "row_prod"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r] = dst[r] * src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 65/75
@instr
class cuda_tk_col_prod(basic_col_reduce_op):
    kittens_op_name = "col_prod"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
        src: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[c] = dst[c] * src[r, c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 66/75
@instr
class cuda_tk_broadcast_row(basic_broadcast_row_op):
    kittens_op_name = "broadcast_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 67/75
@instr
class cuda_tk_broadcast_col(basic_broadcast_col_op):
    kittens_op_name = "broadcast_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 68/75
@instr
class cuda_tk_add_row(basic_broadcast_row_op):
    kittens_op_name = "add_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] += src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 69/75
@instr
class cuda_tk_add_col(basic_broadcast_col_op):
    kittens_op_name = "add_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] += src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 70/75
@instr
class cuda_tk_sub_row(basic_broadcast_row_op):
    kittens_op_name = "sub_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] - src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 71/75
@instr
class cuda_tk_sub_col(basic_broadcast_col_op):
    kittens_op_name = "sub_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] - src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 72/75
@instr
class cuda_tk_mul_row(basic_broadcast_row_op):
    kittens_op_name = "mul_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] * src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 73/75
@instr
class cuda_tk_mul_col(basic_broadcast_col_op):
    kittens_op_name = "mul_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] * src[c]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 74/75
@instr
class cuda_tk_div_row(basic_broadcast_row_op):
    kittens_op_name = "div_row"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][rows],  # @ CudaTkWarpTile(rows, cols, layout="row").col_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] / src[r]


#### Autogenerated by gen_tk_tile_ops.py; do not hand-edit! ####
# Tile op 75/75
@instr
class cuda_tk_div_col(basic_broadcast_col_op):
    kittens_op_name = "div_col"
    valid_num_types = ScalarInfo.same()

    def behavior(
        rows: size,  # Template control value parameter
        cols: size,  # Template control value parameter
        dst: [R][rows, cols],  # @ CudaTkWarpTile(rows, cols, layout="row")
        src: [R][cols],  # @ CudaTkWarpTile(rows, cols, layout="row").row_vec
    ):
        for r in seq(0, rows):
            for c in seq(0, cols):
                dst[r, c] = dst[r, c] / src[c]

# End of file. Prevent black newline reformatting.
