# fmt: off

#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
from __future__ import annotations
from exo.API import instr
from exo.scalars import ScalarInfo, inf

from exo.libs.externs import fabsf, fminf, fmaxf, relu, expf, exp2f, logf, log2f

from .tk_types import *

from .tk_vec_ops_impl import (
    basic_0ary_vec_op,
    basic_copy_layout_vec_op,
    basic_unary_vec_op,
    basic_binary_3op_vec_op,
    basic_binary_lhs_vec_op,
    basic_binary_rhs_vec_op,
    basic_binary_3op_vec_scalar_op,
    basic_binary_lhs_vec_scalar_op,
)

from ..cuda import CudaBasicDeviceVisible



#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
__all__ = [
    "cuda_tk_vec_copy",                     # dst[i] = src[i]
    "cuda_tk_vec_copy_layout",              # dst[i] = src[i]
    "cuda_tk_vec_zero",                     # dst[i] = 0
    "cuda_tk_vec_one",                      # dst[i] = 1
    "cuda_tk_vec_pos_infty",                # dst[i] = inf
    "cuda_tk_vec_neg_infty",                # dst[i] = -inf
    "cuda_tk_vec_pos_inf",                  # For consistency with exo.inf
    "cuda_tk_vec_neg_inf",                  # For consistency with exo.inf
    "cuda_tk_vec_exp",                      # dst[i] = expf(src[i])
    "cuda_tk_vec_exp2",                     # dst[i] = exp2f(src[i])
    "cuda_tk_vec_log",                      # dst[i] = logf(src[i])
    "cuda_tk_vec_log2",                     # dst[i] = log2f(src[i])
    "cuda_tk_vec_abs",                      # dst[i] = fabsf(src[i])
    "cuda_tk_vec_relu",                     # dst[i] = relu(src[i])
]

#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 1/14
@instr
class cuda_tk_vec_copy(basic_unary_vec_op):
    kittens_op_name = "copy"
    valid_num_types = cuda_tk_valid_num_types_all_pairs

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = src[i]


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 2/14
@instr
class cuda_tk_vec_copy_layout(basic_copy_layout_vec_op):
    kittens_op_name = "copy"
    valid_num_types = cuda_tk_valid_num_types_all_pairs

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, dst_layout)
        src: [R][length],  # @ CudaTkWarpVec(length, src_layout)
    ):
        for i in seq(0, length):
            dst[i] = src[i]


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 3/14
@instr
class cuda_tk_vec_zero(basic_0ary_vec_op):
    kittens_op_name = "zero"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = 0


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 4/14
@instr
class cuda_tk_vec_one(basic_0ary_vec_op):
    kittens_op_name = "one"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = 1


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 5/14
@instr
class cuda_tk_vec_pos_infty(basic_0ary_vec_op):
    kittens_op_name = "pos_infty"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = inf


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 6/14
@instr
class cuda_tk_vec_neg_infty(basic_0ary_vec_op):
    kittens_op_name = "neg_infty"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = -inf


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 7/14
cuda_tk_vec_pos_inf = cuda_tk_vec_pos_infty

#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 8/14
cuda_tk_vec_neg_inf = cuda_tk_vec_neg_infty

#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 9/14
@instr
class cuda_tk_vec_exp(basic_unary_vec_op):
    kittens_op_name = "exp"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = expf(src[i])


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 10/14
@instr
class cuda_tk_vec_exp2(basic_unary_vec_op):
    kittens_op_name = "exp2"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = exp2f(src[i])


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 11/14
@instr
class cuda_tk_vec_log(basic_unary_vec_op):
    kittens_op_name = "log"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = logf(src[i])


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 12/14
@instr
class cuda_tk_vec_log2(basic_unary_vec_op):
    kittens_op_name = "log2"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = log2f(src[i])


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 13/14
@instr
class cuda_tk_vec_abs(basic_unary_vec_op):
    kittens_op_name = "abs"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = fabsf(src[i])


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 14/14
@instr
class cuda_tk_vec_relu(basic_unary_vec_op):
    kittens_op_name = "relu"
    valid_num_types = ScalarInfo.same()

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = relu(src[i])

# End of file. Prevent black newline reformatting.
