# fmt: off

#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
from __future__ import annotations
from exo.API import instr
from exo.scalars import ScalarInfo, inf

from exo.libs.externs import fabsf, fminf, fmaxf, relu, expf, exp2f, logf, log2f

from .tk_types import *

from .tk_vec_ops_impl import (
    basic_0ary_vec_op,
    basic_copy_layout_vec_op,
    basic_unary_vec_op,
    basic_binary_3op_vec_op,
    basic_binary_lhs_vec_op,
    basic_binary_rhs_vec_op,
    basic_binary_3op_vec_scalar_op,
    basic_binary_lhs_vec_scalar_op,
)

from ..cuda import CudaBasicDeviceVisible



#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
__all__ = [
    "cuda_tk_vec_copy",                     # dst[i] = src[i]
    "cuda_tk_vec_copy_layout",              # dst[i] = src[i]
]

#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 1/2
@instr
class cuda_tk_vec_copy(basic_unary_vec_op):
    kittens_op_name = "copy"
    valid_num_types = cuda_tk_valid_num_types_all_pairs

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, layout)
        src: [R][length],  # @ CudaTkWarpVec(length, layout)
    ):
        for i in seq(0, length):
            dst[i] = src[i]


#### Autogenerated by gen_tk_vec_ops.py; do not hand-edit! ####
# Vec op 2/2
@instr
class cuda_tk_vec_copy_layout(basic_copy_layout_vec_op):
    kittens_op_name = "copy"
    valid_num_types = cuda_tk_valid_num_types_all_pairs

    def behavior(
        length: size,
        dst: [R][length],  # @ CudaTkWarpVec(length, dst_layout)
        src: [R][length],  # @ CudaTkWarpVec(length, src_layout)
    ):
        for i in seq(0, length):
            dst[i] = src[i]

# End of file. Prevent black newline reformatting.
