# fmt: off
# Code for generating tk_shared_to_register.py
# Unfortunately, the 2D RMEM / 3D SMEM tiling mismatch exceeds the limits
# of what Exo-GPU instruction templates can express, due to affine indexing restrictions.
# So David Zhao Akeley has to implement this ad-hoc metaprogramming.

import os

f = open(os.path.join(os.path.split(__file__)[0], "tk_shared_to_register.py"), "w")


def forbid_trailing_spaces(line):
    assert not line.endswith(" "), line
    return line


def write_chunk(chunk):
    f.write("\n")
    f.write("######################################################################\n")
    f.write("# Autogenerated by gen_tk_shared_to_register.py; do not hand-edit!!! #\n")
    f.write("######################################################################\n")

    lines = [forbid_trailing_spaces(line) for line in chunk.split("\n")]
    for line in lines:
        f.write(line)
        f.write("\n")


f.write("# fmt: off\n")

write_chunk('''\
from __future__ import annotations
from exo.API import instr

from .tk_shared_to_register_impl import (
    make_tk_load_rs_base,
    make_tk_store_rs_base,
    get_tk_load_rs_instr_impl,
    get_tk_store_rs_instr_impl,
)

tk_load_rs_instr_dict = {}
tk_store_rs_instr_dict = {}

__all__ = []
''')


for inner_cols in (8, 16, 32, 64, 128):
    write_chunk(f'''\
@instr
class tk_load_rs_inner_cols_{inner_cols}(make_tk_load_rs_base({inner_cols})):
    """Warp copies 2D [rows, outer_cols * {inner_cols}] RMEM tile to SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, {inner_cols}] tile,
    with RMEM[r, c] mapped to SMEM[c / {inner_cols}, r, c % {inner_cols}].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][rows, {inner_cols} * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
        src: [R][outer_cols, rows, {inner_cols}],  # @ Sm90_SmemSwizzled({inner_cols} * sizeof(R))
    ):
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, {inner_cols}):
                    dst[row, outer_col * {inner_cols} + inner_col] = src[outer_col, row, inner_col]

@instr
class tk_store_rs_inner_cols_{inner_cols}(make_tk_store_rs_base({inner_cols})):
    """Warp copies 2D [rows, outer_cols * {inner_cols}] RMEM tile from SMEM.

    The SMEM tile is a swizzled 3D [outer_cols, rows, {inner_cols}] tile,
    with RMEM[r, c] mapped to SMEM[c / {inner_cols}, r, c % {inner_cols}].

    """
    def behavior(
        rows: size,        # instance parameter
        outer_cols: size,  # instance parameter
        dst: [R][outer_cols, rows, {inner_cols}],  # @ Sm90_SmemSwizzled({inner_cols} * sizeof(R))
        src: [R][rows, {inner_cols} * outer_cols], # @ CudaTkWarpTile(rows, cols, "row")
    ):
        for row in seq(0, rows):
            for outer_col in seq(0, outer_cols):
                for inner_col in seq(0, {inner_cols}):
                    dst[outer_col, row, inner_col] = src[row, outer_col * {inner_cols} + inner_col]

__all__.append("tk_load_rs_inner_cols_{inner_cols}")
__all__.append("tk_store_rs_inner_cols_{inner_cols}")
tk_load_rs_instr_dict[{inner_cols}] = tk_load_rs_inner_cols_{inner_cols}
tk_store_rs_instr_dict[{inner_cols}] = tk_store_rs_inner_cols_{inner_cols}
''')


f.write("# End of file. Prevent black newline reformatting.\n")
f.close()
