name: CI
on:
  push:
    branches: [ 'main' ]
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-14 ]
        include:
          - runner: ubuntu-latest
            CC: clang-13
            CXX: clang++-13
            CLANG: clang-13
          - runner: macos-14
            CC: clang # This will be system AppleClang
            CXX: clang++ # This will be system AppleClang
            CLANG: /usr/local/opt/llvm/bin/clang
    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}
      CLANG: ${{matrix.CLANG}}
    runs-on: ${{matrix.runner}}
    steps:
      - name: Checkout sources (including submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install tox==3.24.5

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Setup SDE binaries
        if: runner.os != 'macOS'
        uses: petarpetrovt/setup-sde@v2.3

      - name: Install Clang 13 (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 13

      - name: Install Clang 13 (macOS)
        if: runner.os == 'macOS'
        run: brew install llvm@13

      - name: Run tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
