name: CI
on:
  push:
    branches: [ 'main' ]
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-14 ]
        include:
          - runner: ubuntu-latest
            CC: clang-17
            CXX: clang++-17
            CLANG: clang-17
          - runner: macos-14
            CC: clang # This will be system AppleClang
            CXX: clang++ # This will be system AppleClang
            CLANG: /usr/local/opt/llvm/bin/clang
    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}
      CLANG: ${{matrix.CLANG}}
    runs-on: ${{matrix.runner}}
    steps:
      - name: Checkout sources (including submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python dependencies
        run: uv sync --all-groups --no-install-project

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Setup SDE binaries
        if: runner.os != 'macOS'
        uses: petarpetrovt/setup-sde@v2.4
        with:
          environmentVariableName: 'SDE_PATH'
          sdeVersion: '9.33.0'

      - name: Install Clang 17 (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17

      - name: Install Clang 17 (macOS)
        if: runner.os == 'macOS'
        run: brew install llvm@17

      - name: Run tox
        run: uv run tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
